/* 🤖 this file was generated by svg-to-ts*/
import { upIconAccountsPayableLarge } from './upIcon-accounts-payable-large.icon';
import { upIconAccountsPayableMedium } from './upIcon-accounts-payable-medium.icon';
import { upIconAccountsReceivableLarge } from './upIcon-accounts-receivable-large.icon';
import { upIconAccountsReceivableMedium } from './upIcon-accounts-receivable-medium.icon';
import { upIconAddSmall } from './upIcon-add-small.icon';
import { upIconAddressMedium } from './upIcon-address-medium.icon';
import { upIconAdmin } from './upIcon-admin.icon';
import { upIconAlertBellMedium } from './upIcon-alert-bell-medium.icon';
import { upIconAlertErrorMedium } from './upIcon-alert-error-medium.icon';
import { upIconAlertErrorSmall } from './upIcon-alert-error-small.icon';
import { upIconAlertHelpMedium } from './upIcon-alert-help-medium.icon';
import { upIconAlertHelpSmall } from './upIcon-alert-help-small.icon';
import { upIconAlertInfoMedium } from './upIcon-alert-info-medium.icon';
import { upIconAlertInfoSmall } from './upIcon-alert-info-small.icon';
import { upIconAlertSuccessMedium } from './upIcon-alert-success-medium.icon';
import { upIconAlertSuccessSmall } from './upIcon-alert-success-small.icon';
import { upIconAlertWarningMedium } from './upIcon-alert-warning-medium.icon';
import { upIconAlertWarningSmall } from './upIcon-alert-warning-small.icon';
import { upIconAlertsMedium } from './upIcon-alerts-medium.icon';
import { upIconAmountLessThan30DMedium } from './upIcon-amount-less-than-30d-medium.icon';
import { upIconAmountMoreThan30DMedium } from './upIcon-amount-more-than-30d-medium.icon';
import { upIconAmountOverdueMedium } from './upIcon-amount-overdue-medium.icon';
import { upIconAmountTotalDollarMedium } from './upIcon-amount-total-dollar-medium.icon';
import { upIconAmountTotalEuroMedium } from './upIcon-amount-total-euro-medium.icon';
import { upIconAmountTotalPoundMedium } from './upIcon-amount-total-pound-medium.icon';
import { upIconAmountTotalYenMedium } from './upIcon-amount-total-yen-medium.icon';
import { upIconApproveDocumentMedium } from './upIcon-approve-document-medium.icon';
import { upIconAppsLarge } from './upIcon-apps-large.icon';
import { upIconAppsMedium } from './upIcon-apps-medium.icon';
import { upIconArchiveLarge } from './upIcon-archive-large.icon';
import { upIconArchiveMedium } from './upIcon-archive-medium.icon';
import { upIconArrowDownMedium } from './upIcon-arrow-down-medium.icon';
import { upIconArrowLeftMedium } from './upIcon-arrow-left-medium.icon';
import { upIconArrowRightMedium } from './upIcon-arrow-right-medium.icon';
import { upIconArrowUpMedium } from './upIcon-arrow-up-medium.icon';
import { upIconAttachmentMedium } from './upIcon-attachment-medium.icon';
import { upIconAttachmentSmall } from './upIcon-attachment-small.icon';
import { upIconAuthenticationLarge } from './upIcon-authentication-large.icon';
import { upIconBackArrowMedium } from './upIcon-back-arrow-medium.icon';
import { upIconBadgeMedium } from './upIcon-badge-medium.icon';
import { upIconBankAccountsLarge } from './upIcon-bank-accounts-large.icon';
import { upIconBankAccountsMedium } from './upIcon-bank-accounts-medium.icon';
import { upIconCalendarSmall } from './upIcon-calendar-small.icon';
import { upIconCancelChangesMedium } from './upIcon-cancel-changes-medium.icon';
import { upIconCatalog } from './upIcon-catalog.icon';
import { upIconChangeAccountMedium } from './upIcon-change-account-medium.icon';
import { upIconChangePhotoMedium } from './upIcon-change-photo-medium.icon';
import { upIconCheckMarkMedium } from './upIcon-check-mark-medium.icon';
import { upIconChevronDownMedium } from './upIcon-chevron-down-medium.icon';
import { upIconChevronDownSmall } from './upIcon-chevron-down-small.icon';
import { upIconChevronLeftMedium } from './upIcon-chevron-left-medium.icon';
import { upIconChevronLeftSmall } from './upIcon-chevron-left-small.icon';
import { upIconChevronRightMedium } from './upIcon-chevron-right-medium.icon';
import { upIconChevronRightSmall } from './upIcon-chevron-right-small.icon';
import { upIconChevronUpMedium } from './upIcon-chevron-up-medium.icon';
import { upIconChevronUpSmall } from './upIcon-chevron-up-small.icon';
import { upIconCleanUpMedium } from './upIcon-clean-up-medium.icon';
import { upIconClearSmall } from './upIcon-clear-small.icon';
import { upIconClientsLarge } from './upIcon-clients-large.icon';
import { upIconClientsMedium } from './upIcon-clients-medium.icon';
import { upIconClients } from './upIcon-clients.icon';
import { upIconCloseMedium } from './upIcon-close-medium.icon';
import { upIconCloseSmall } from './upIcon-close-small.icon';
import { upIconCollapseMedium } from './upIcon-collapse-medium.icon';
import { upIconCommentAppendedMedium } from './upIcon-comment-appended-medium.icon';
import { upIconCommentsMedium } from './upIcon-comments-medium.icon';
import { upIconCompanyMedium } from './upIcon-company-medium.icon';
import { upIconCompanySmall } from './upIcon-company-small.icon';
import { upIconCompareMedium } from './upIcon-compare-medium.icon';
import { upIconConfigMedium } from './upIcon-config-medium.icon';
import { upIconCopyMedium } from './upIcon-copy-medium.icon';
import { upIconCountryPlaceholder } from './upIcon-country-placeholder.icon';
import { upIconCountrySelected } from './upIcon-country-selected.icon';
import { upIconDeactivateMedium } from './upIcon-deactivate-medium.icon';
import { upIconDeleteMedium } from './upIcon-delete-medium.icon';
import { upIconDensityCondensedSmall } from './upIcon-density-condensed-small.icon';
import { upIconDensityRegularSmall } from './upIcon-density-regular-small.icon';
import { upIconDensityRelaxedSmall } from './upIcon-density-relaxed-small.icon';
import { upIconDetailsMedium } from './upIcon-details-medium.icon';
import { upIconDiscount } from './upIcon-discount.icon';
import { upIconDocCenterLarge } from './upIcon-doc-center-large.icon';
import { upIconDocCenterMedium } from './upIcon-doc-center-medium.icon';
import { upIconDocumentAltMedium } from './upIcon-document-alt-medium.icon';
import { upIconDocumentLinkMedium } from './upIcon-document-link-medium.icon';
import { upIconDocumentNotLinkedMedium } from './upIcon-document-not-linked-medium.icon';
import { upIconDocumentPdfMedium } from './upIcon-document-pdf-medium.icon';
import { upIconDocument } from './upIcon-document.icon';
import { upIconDoneMedium } from './upIcon-done-medium.icon';
import { upIconDownloadAttachmentMedium } from './upIcon-download-attachment-medium.icon';
import { upIconDownloadMedium } from './upIcon-download-medium.icon';
import { upIconEditMedium } from './upIcon-edit-medium.icon';
import { upIconEmailMedium } from './upIcon-email-medium.icon';
import { upIconExpandMedium } from './upIcon-expand-medium.icon';
import { upIconExportMedium } from './upIcon-export-medium.icon';
import { upIconFavouriteMedium } from './upIcon-favourite-medium.icon';
import { upIconFederatedIdentityLarge } from './upIcon-federated-identity-large.icon';
import { upIconFilterActiveMedium } from './upIcon-filter-active-medium.icon';
import { upIconFilterSmall } from './upIcon-filter-small.icon';
import { upIconFirstPageLarge } from './upIcon-first-page-large.icon';
import { upIconFirstPageMedium } from './upIcon-first-page-medium.icon';
import { upIconFirstPageSmall } from './upIcon-first-page-small.icon';
import { upIconFitToHeightMedium } from './upIcon-fit-to-height-medium.icon';
import { upIconFitToWidthMedium } from './upIcon-fit-to-width-medium.icon';
import { upIconFullScreenMedium } from './upIcon-full-screen-medium.icon';
import { upIconGoToMedium } from './upIcon-go-to-medium.icon';
import { upIconGridMedium } from './upIcon-grid-medium.icon';
import { upIconHideSmall } from './upIcon-hide-small.icon';
import { upIconHomeLarge } from './upIcon-home-large.icon';
import { upIconHomeMedium } from './upIcon-home-medium.icon';
import { upIconIdeaMedium } from './upIcon-idea-medium.icon';
import { upIconImageMedium } from './upIcon-image-medium.icon';
import { upIconImportMedium } from './upIcon-import-medium.icon';
import { upIconInboxMedium } from './upIcon-inbox-medium.icon';
import { upIconInviteMedium } from './upIcon-invite-medium.icon';
import { upIconInvoiceMedium } from './upIcon-invoice-medium.icon';
import { upIconKeycloakLarge } from './upIcon-keycloak-large.icon';
import { upIconKickstartMedium } from './upIcon-kickstart-medium.icon';
import { upIconLanguageMedium } from './upIcon-language-medium.icon';
import { upIconLastPageLarge } from './upIcon-last-page-large.icon';
import { upIconLastPageMedium } from './upIcon-last-page-medium.icon';
import { upIconLastPageSmall } from './upIcon-last-page-small.icon';
import { upIconLeadingArrowSmall } from './upIcon-leading-arrow-small.icon';
import { upIconLinkMedium } from './upIcon-link-medium.icon';
import { upIconLockMedium } from './upIcon-lock-medium.icon';
import { upIconLogoAcertaWhite } from './upIcon-logo-acerta-white.icon';
import { upIconLogoSdworxWhite } from './upIcon-logo-sdworx-white.icon';
import { upIconLogoutSmall } from './upIcon-logout-small.icon';
import { upIconMaintenanceLarge } from './upIcon-maintenance-large.icon';
import { upIconMarkAsAcceptMedium } from './upIcon-mark-as-accept-medium.icon';
import { upIconMarkAsPaidMedium } from './upIcon-mark-as-paid-medium.icon';
import { upIconMessageMedium } from './upIcon-message-medium.icon';
import { upIconMinusMedium } from './upIcon-minus-medium.icon';
import { upIconMissingDocumentLarge } from './upIcon-missing-document-large.icon';
import { upIconMissingState } from './upIcon-missing-state.icon';
import { upIconMoveLeftMedium } from './upIcon-move-left-medium.icon';
import { upIconMoveRightMedium } from './upIcon-move-right-medium.icon';
import { upIconMoveToMedium } from './upIcon-move-to-medium.icon';
import { upIconMultiMedium } from './upIcon-multi-medium.icon';
import { upIconMyAccountLarge } from './upIcon-my-account-large.icon';
import { upIconNetworkMedium } from './upIcon-network-medium.icon';
import { upIconNewFolderMedium } from './upIcon-new-folder-medium.icon';
import { upIconNewsMedium } from './upIcon-news-medium.icon';
import { upIconNotificationErrorSmall } from './upIcon-notification-error-small.icon';
import { upIconOutboxMedium } from './upIcon-outbox-medium.icon';
import { upIconPayMedium } from './upIcon-pay-medium.icon';
import { upIconPlusMedium } from './upIcon-plus-medium.icon';
import { upIconProcessMedium } from './upIcon-process-medium.icon';
import { upIconProductCatalogMedium } from './upIcon-product-catalog-medium.icon';
import { upIconPurchases } from './upIcon-purchases.icon';
import { upIconRearrangeMedium } from './upIcon-rearrange-medium.icon';
import { upIconRestoreMedium } from './upIcon-restore-medium.icon';
import { upIconSaveMedium } from './upIcon-save-medium.icon';
import { upIconScanMedium } from './upIcon-scan-medium.icon';
import { upIconSearchMedium } from './upIcon-search-medium.icon';
import { upIconSearchSmall } from './upIcon-search-small.icon';
import { upIconSecurityLarge } from './upIcon-security-large.icon';
import { upIconServerRelatedLarge } from './upIcon-server-related-large.icon';
import { upIconSessionsMedium } from './upIcon-sessions-medium.icon';
import { upIconSettingsLarge } from './upIcon-settings-large.icon';
import { upIconSettingsMedium } from './upIcon-settings-medium.icon';
import { upIconShowSmall } from './upIcon-show-small.icon';
import { upIconSortDownSmall } from './upIcon-sort-down-small.icon';
import { upIconSortMedium } from './upIcon-sort-medium.icon';
import { upIconSortSmall } from './upIcon-sort-small.icon';
import { upIconSortUpSmall } from './upIcon-sort-up-small.icon';
import { upIconSpinnerMedium } from './upIcon-spinner-medium.icon';
import { upIconSplitMedium } from './upIcon-split-medium.icon';
import { upIconSubscriptions } from './upIcon-subscriptions.icon';
import { upIconSyncMedium } from './upIcon-sync-medium.icon';
import { upIconTakePhotoMedium } from './upIcon-take-photo-medium.icon';
import { upIconTasksLarge } from './upIcon-tasks-large.icon';
import { upIconTasksMedium } from './upIcon-tasks-medium.icon';
import { upIconTemplate } from './upIcon-template.icon';
import { upIconTrailingArrowSmall } from './upIcon-trailing-arrow-small.icon';
import { upIconTrailingIcon } from './upIcon-trailing-icon.icon';
import { upIconUpLogoName } from './upIcon-up-logo-name.icon';
import { upIconUpLogoShape } from './upIcon-up-logo-shape.icon';
import { upIconUpLogoTagline } from './upIcon-up-logo-tagline.icon';
import { upIconUploadMedium } from './upIcon-upload-medium.icon';
import { upIconUserMedium } from './upIcon-user-medium.icon';
import { upIconUserSmall } from './upIcon-user-small.icon';
import { upIconVatExemptMedium } from './upIcon-vat-exempt-medium.icon';
import { upIconVerticalDotsMedium } from './upIcon-vertical-dots-medium.icon';
import { upIconWarningIcon } from './upIcon-warning-icon.icon';
import { upIconZoomInDisabledMedium } from './upIcon-zoom-in-disabled-medium.icon';
import { upIconZoomInMedium } from './upIcon-zoom-in-medium.icon';
import { upIconZoomOutMedium } from './upIcon-zoom-out-medium.icon';
import { upIconAd } from './upIcon-AD.icon';
import { upIconAe } from './upIcon-AE.icon';
import { upIconAf } from './upIcon-AF.icon';
import { upIconAg } from './upIcon-AG.icon';
import { upIconAi } from './upIcon-AI.icon';
import { upIconAl } from './upIcon-AL.icon';
import { upIconAm } from './upIcon-AM.icon';
import { upIconAo } from './upIcon-AO.icon';
import { upIconAr } from './upIcon-AR.icon';
import { upIconAs } from './upIcon-AS.icon';
import { upIconAt } from './upIcon-AT.icon';
import { upIconAu } from './upIcon-AU.icon';
import { upIconAw } from './upIcon-AW.icon';
import { upIconAx } from './upIcon-AX.icon';
import { upIconAz } from './upIcon-AZ.icon';
import { upIconBa } from './upIcon-BA.icon';
import { upIconBb } from './upIcon-BB.icon';
import { upIconBd } from './upIcon-BD.icon';
import { upIconBe } from './upIcon-BE.icon';
import { upIconBf } from './upIcon-BF.icon';
import { upIconBg } from './upIcon-BG.icon';
import { upIconBh } from './upIcon-BH.icon';
import { upIconBi } from './upIcon-BI.icon';
import { upIconBj } from './upIcon-BJ.icon';
import { upIconBm } from './upIcon-BM.icon';
import { upIconBn } from './upIcon-BN.icon';
import { upIconBo } from './upIcon-BO.icon';
import { upIconBr } from './upIcon-BR.icon';
import { upIconBs } from './upIcon-BS.icon';
import { upIconBt } from './upIcon-BT.icon';
import { upIconBw } from './upIcon-BW.icon';
import { upIconBy } from './upIcon-BY.icon';
import { upIconBz } from './upIcon-BZ.icon';
import { upIconCa } from './upIcon-CA.icon';
import { upIconCc } from './upIcon-CC.icon';
import { upIconCd } from './upIcon-CD.icon';
import { upIconCf } from './upIcon-CF.icon';
import { upIconCg } from './upIcon-CG.icon';
import { upIconCh } from './upIcon-CH.icon';
import { upIconCi } from './upIcon-CI.icon';
import { upIconCk } from './upIcon-CK.icon';
import { upIconCl } from './upIcon-CL.icon';
import { upIconCm } from './upIcon-CM.icon';
import { upIconCn } from './upIcon-CN.icon';
import { upIconCo } from './upIcon-CO.icon';
import { upIconCr } from './upIcon-CR.icon';
import { upIconCu } from './upIcon-CU.icon';
import { upIconCv } from './upIcon-CV.icon';
import { upIconCx } from './upIcon-CX.icon';
import { upIconCy } from './upIcon-CY.icon';
import { upIconCz } from './upIcon-CZ.icon';
import { upIconDe } from './upIcon-DE.icon';
import { upIconDj } from './upIcon-DJ.icon';
import { upIconDk } from './upIcon-DK.icon';
import { upIconDm } from './upIcon-DM.icon';
import { upIconDo } from './upIcon-DO.icon';
import { upIconDz } from './upIcon-DZ.icon';
import { upIconEc } from './upIcon-EC.icon';
import { upIconEe } from './upIcon-EE.icon';
import { upIconEg } from './upIcon-EG.icon';
import { upIconEh } from './upIcon-EH.icon';
import { upIconEr } from './upIcon-ER.icon';
import { upIconEs } from './upIcon-ES.icon';
import { upIconEt } from './upIcon-ET.icon';
import { upIconFi } from './upIcon-FI.icon';
import { upIconFj } from './upIcon-FJ.icon';
import { upIconFk } from './upIcon-FK.icon';
import { upIconFm } from './upIcon-FM.icon';
import { upIconFo } from './upIcon-FO.icon';
import { upIconFr } from './upIcon-FR.icon';
import { upIconGa } from './upIcon-GA.icon';
import { upIconGb } from './upIcon-GB.icon';
import { upIconGd } from './upIcon-GD.icon';
import { upIconGe } from './upIcon-GE.icon';
import { upIconGg } from './upIcon-GG.icon';
import { upIconGh } from './upIcon-GH.icon';
import { upIconGi } from './upIcon-GI.icon';
import { upIconGl } from './upIcon-GL.icon';
import { upIconGm } from './upIcon-GM.icon';
import { upIconGn } from './upIcon-GN.icon';
import { upIconGq } from './upIcon-GQ.icon';
import { upIconGr } from './upIcon-GR.icon';
import { upIconGt } from './upIcon-GT.icon';
import { upIconGu } from './upIcon-GU.icon';
import { upIconGw } from './upIcon-GW.icon';
import { upIconGy } from './upIcon-GY.icon';
import { upIconHk } from './upIcon-HK.icon';
import { upIconHn } from './upIcon-HN.icon';
import { upIconHr } from './upIcon-HR.icon';
import { upIconHt } from './upIcon-HT.icon';
import { upIconHu } from './upIcon-HU.icon';
import { upIconId } from './upIcon-ID.icon';
import { upIconIe } from './upIcon-IE.icon';
import { upIconIl } from './upIcon-IL.icon';
import { upIconIm } from './upIcon-IM.icon';
import { upIconIn } from './upIcon-IN.icon';
import { upIconIo } from './upIcon-IO.icon';
import { upIconIq } from './upIcon-IQ.icon';
import { upIconIr } from './upIcon-IR.icon';
import { upIconIs } from './upIcon-IS.icon';
import { upIconIt } from './upIcon-IT.icon';
import { upIconJe } from './upIcon-JE.icon';
import { upIconJm } from './upIcon-JM.icon';
import { upIconJo } from './upIcon-JO.icon';
import { upIconJp } from './upIcon-JP.icon';
import { upIconKe } from './upIcon-KE.icon';
import { upIconKg } from './upIcon-KG.icon';
import { upIconKh } from './upIcon-KH.icon';
import { upIconKi } from './upIcon-KI.icon';
import { upIconKm } from './upIcon-KM.icon';
import { upIconKn } from './upIcon-KN.icon';
import { upIconKp } from './upIcon-KP.icon';
import { upIconKw } from './upIcon-KW.icon';
import { upIconKy } from './upIcon-KY.icon';
import { upIconKz } from './upIcon-KZ.icon';
import { upIconLa } from './upIcon-LA.icon';
import { upIconLb } from './upIcon-LB.icon';
import { upIconLc } from './upIcon-LC.icon';
import { upIconLi } from './upIcon-LI.icon';
import { upIconLk } from './upIcon-LK.icon';
import { upIconLr } from './upIcon-LR.icon';
import { upIconLs } from './upIcon-LS.icon';
import { upIconLt } from './upIcon-LT.icon';
import { upIconLu } from './upIcon-LU.icon';
import { upIconLv } from './upIcon-LV.icon';
import { upIconLy } from './upIcon-LY.icon';
import { upIconMa } from './upIcon-MA.icon';
import { upIconMc } from './upIcon-MC.icon';
import { upIconMd } from './upIcon-MD.icon';
import { upIconMe } from './upIcon-ME.icon';
import { upIconMf } from './upIcon-MF.icon';
import { upIconMg } from './upIcon-MG.icon';
import { upIconMh } from './upIcon-MH.icon';
import { upIconMk } from './upIcon-MK.icon';
import { upIconMl } from './upIcon-ML.icon';
import { upIconMm } from './upIcon-MM.icon';
import { upIconMn } from './upIcon-MN.icon';
import { upIconMo } from './upIcon-MO.icon';
import { upIconMp } from './upIcon-MP.icon';
import { upIconMq } from './upIcon-MQ.icon';
import { upIconMr } from './upIcon-MR.icon';
import { upIconMs } from './upIcon-MS.icon';
import { upIconMt } from './upIcon-MT.icon';
import { upIconMu } from './upIcon-MU.icon';
import { upIconMv } from './upIcon-MV.icon';
import { upIconMw } from './upIcon-MW.icon';
import { upIconMx } from './upIcon-MX.icon';
import { upIconMy } from './upIcon-MY.icon';
import { upIconMz } from './upIcon-MZ.icon';
import { upIconNa } from './upIcon-NA.icon';
import { upIconNe } from './upIcon-NE.icon';
import { upIconNf } from './upIcon-NF.icon';
import { upIconNg } from './upIcon-NG.icon';
import { upIconNi } from './upIcon-NI.icon';
import { upIconNl } from './upIcon-NL.icon';
import { upIconNo } from './upIcon-NO.icon';
import { upIconNp } from './upIcon-NP.icon';
import { upIconNr } from './upIcon-NR.icon';
import { upIconNu } from './upIcon-NU.icon';
import { upIconNz } from './upIcon-NZ.icon';
import { upIconOm } from './upIcon-OM.icon';
import { upIconPa } from './upIcon-PA.icon';
import { upIconPe } from './upIcon-PE.icon';
import { upIconPf } from './upIcon-PF.icon';
import { upIconPg } from './upIcon-PG.icon';
import { upIconPh } from './upIcon-PH.icon';
import { upIconPk } from './upIcon-PK.icon';
import { upIconPl } from './upIcon-PL.icon';
import { upIconPn } from './upIcon-PN.icon';
import { upIconPr } from './upIcon-PR.icon';
import { upIconPs } from './upIcon-PS.icon';
import { upIconPt } from './upIcon-PT.icon';
import { upIconPw } from './upIcon-PW.icon';
import { upIconPy } from './upIcon-PY.icon';
import { upIconQa } from './upIcon-QA.icon';
import { upIconRo } from './upIcon-RO.icon';
import { upIconRs } from './upIcon-RS.icon';
import { upIconRu } from './upIcon-RU.icon';
import { upIconRw } from './upIcon-RW.icon';
import { upIconSa } from './upIcon-SA.icon';
import { upIconSb } from './upIcon-SB.icon';
import { upIconSc } from './upIcon-SC.icon';
import { upIconSd } from './upIcon-SD.icon';
import { upIconSe } from './upIcon-SE.icon';
import { upIconSg } from './upIcon-SG.icon';
import { upIconSi } from './upIcon-SI.icon';
import { upIconSk } from './upIcon-SK.icon';
import { upIconSl } from './upIcon-SL.icon';
import { upIconSm } from './upIcon-SM.icon';
import { upIconSn } from './upIcon-SN.icon';
import { upIconSo } from './upIcon-SO.icon';
import { upIconSr } from './upIcon-SR.icon';
import { upIconSs } from './upIcon-SS.icon';
import { upIconSt } from './upIcon-ST.icon';
import { upIconSv } from './upIcon-SV.icon';
import { upIconSy } from './upIcon-SY.icon';
import { upIconSz } from './upIcon-SZ.icon';
import { upIconTc } from './upIcon-TC.icon';
import { upIconTd } from './upIcon-TD.icon';
import { upIconTg } from './upIcon-TG.icon';
import { upIconTh } from './upIcon-TH.icon';
import { upIconTj } from './upIcon-TJ.icon';
import { upIconTk } from './upIcon-TK.icon';
import { upIconTl } from './upIcon-TL.icon';
import { upIconTm } from './upIcon-TM.icon';
import { upIconTn } from './upIcon-TN.icon';
import { upIconTo } from './upIcon-TO.icon';
import { upIconTr } from './upIcon-TR.icon';
import { upIconTt } from './upIcon-TT.icon';
import { upIconTv } from './upIcon-TV.icon';
import { upIconTw } from './upIcon-TW.icon';
import { upIconTz } from './upIcon-TZ.icon';
import { upIconUa } from './upIcon-UA.icon';
import { upIconUg } from './upIcon-UG.icon';
import { upIconUs } from './upIcon-US.icon';
import { upIconUy } from './upIcon-UY.icon';
import { upIconUz } from './upIcon-UZ.icon';
import { upIconVa } from './upIcon-VA.icon';
import { upIconVc } from './upIcon-VC.icon';
import { upIconVe } from './upIcon-VE.icon';
import { upIconVg } from './upIcon-VG.icon';
import { upIconVi } from './upIcon-VI.icon';
import { upIconVn } from './upIcon-VN.icon';
import { upIconVu } from './upIcon-VU.icon';
import { upIconWs } from './upIcon-WS.icon';
import { upIconYe } from './upIcon-YE.icon';
import { upIconZa } from './upIcon-ZA.icon';
import { upIconZm } from './upIcon-ZM.icon';
import { upIconZw } from './upIcon-ZW.icon';
export const completeIconSet = [
    upIconAccountsPayableLarge,
    upIconAccountsPayableMedium,
    upIconAccountsReceivableLarge,
    upIconAccountsReceivableMedium,
    upIconAddSmall,
    upIconAddressMedium,
    upIconAdmin,
    upIconAlertBellMedium,
    upIconAlertErrorMedium,
    upIconAlertErrorSmall,
    upIconAlertHelpMedium,
    upIconAlertHelpSmall,
    upIconAlertInfoMedium,
    upIconAlertInfoSmall,
    upIconAlertSuccessMedium,
    upIconAlertSuccessSmall,
    upIconAlertWarningMedium,
    upIconAlertWarningSmall,
    upIconAlertsMedium,
    upIconAmountLessThan30DMedium,
    upIconAmountMoreThan30DMedium,
    upIconAmountOverdueMedium,
    upIconAmountTotalDollarMedium,
    upIconAmountTotalEuroMedium,
    upIconAmountTotalPoundMedium,
    upIconAmountTotalYenMedium,
    upIconApproveDocumentMedium,
    upIconAppsLarge,
    upIconAppsMedium,
    upIconArchiveLarge,
    upIconArchiveMedium,
    upIconArrowDownMedium,
    upIconArrowLeftMedium,
    upIconArrowRightMedium,
    upIconArrowUpMedium,
    upIconAttachmentMedium,
    upIconAttachmentSmall,
    upIconAuthenticationLarge,
    upIconBackArrowMedium,
    upIconBadgeMedium,
    upIconBankAccountsLarge,
    upIconBankAccountsMedium,
    upIconCalendarSmall,
    upIconCancelChangesMedium,
    upIconCatalog,
    upIconChangeAccountMedium,
    upIconChangePhotoMedium,
    upIconCheckMarkMedium,
    upIconChevronDownMedium,
    upIconChevronDownSmall,
    upIconChevronLeftMedium,
    upIconChevronLeftSmall,
    upIconChevronRightMedium,
    upIconChevronRightSmall,
    upIconChevronUpMedium,
    upIconChevronUpSmall,
    upIconCleanUpMedium,
    upIconClearSmall,
    upIconClientsLarge,
    upIconClientsMedium,
    upIconClients,
    upIconCloseMedium,
    upIconCloseSmall,
    upIconCollapseMedium,
    upIconCommentAppendedMedium,
    upIconCommentsMedium,
    upIconCompanyMedium,
    upIconCompanySmall,
    upIconCompareMedium,
    upIconConfigMedium,
    upIconCopyMedium,
    upIconCountryPlaceholder,
    upIconCountrySelected,
    upIconDeactivateMedium,
    upIconDeleteMedium,
    upIconDensityCondensedSmall,
    upIconDensityRegularSmall,
    upIconDensityRelaxedSmall,
    upIconDetailsMedium,
    upIconDiscount,
    upIconDocCenterLarge,
    upIconDocCenterMedium,
    upIconDocumentAltMedium,
    upIconDocumentLinkMedium,
    upIconDocumentNotLinkedMedium,
    upIconDocumentPdfMedium,
    upIconDocument,
    upIconDoneMedium,
    upIconDownloadAttachmentMedium,
    upIconDownloadMedium,
    upIconEditMedium,
    upIconEmailMedium,
    upIconExpandMedium,
    upIconExportMedium,
    upIconFavouriteMedium,
    upIconFederatedIdentityLarge,
    upIconFilterActiveMedium,
    upIconFilterSmall,
    upIconFirstPageLarge,
    upIconFirstPageMedium,
    upIconFirstPageSmall,
    upIconFitToHeightMedium,
    upIconFitToWidthMedium,
    upIconFullScreenMedium,
    upIconGoToMedium,
    upIconGridMedium,
    upIconHideSmall,
    upIconHomeLarge,
    upIconHomeMedium,
    upIconIdeaMedium,
    upIconImageMedium,
    upIconImportMedium,
    upIconInboxMedium,
    upIconInviteMedium,
    upIconInvoiceMedium,
    upIconKeycloakLarge,
    upIconKickstartMedium,
    upIconLanguageMedium,
    upIconLastPageLarge,
    upIconLastPageMedium,
    upIconLastPageSmall,
    upIconLeadingArrowSmall,
    upIconLinkMedium,
    upIconLockMedium,
    upIconLogoAcertaWhite,
    upIconLogoSdworxWhite,
    upIconLogoutSmall,
    upIconMaintenanceLarge,
    upIconMarkAsAcceptMedium,
    upIconMarkAsPaidMedium,
    upIconMessageMedium,
    upIconMinusMedium,
    upIconMissingDocumentLarge,
    upIconMissingState,
    upIconMoveLeftMedium,
    upIconMoveRightMedium,
    upIconMoveToMedium,
    upIconMultiMedium,
    upIconMyAccountLarge,
    upIconNetworkMedium,
    upIconNewFolderMedium,
    upIconNewsMedium,
    upIconNotificationErrorSmall,
    upIconOutboxMedium,
    upIconPayMedium,
    upIconPlusMedium,
    upIconProcessMedium,
    upIconProductCatalogMedium,
    upIconPurchases,
    upIconRearrangeMedium,
    upIconRestoreMedium,
    upIconSaveMedium,
    upIconScanMedium,
    upIconSearchMedium,
    upIconSearchSmall,
    upIconSecurityLarge,
    upIconServerRelatedLarge,
    upIconSessionsMedium,
    upIconSettingsLarge,
    upIconSettingsMedium,
    upIconShowSmall,
    upIconSortDownSmall,
    upIconSortMedium,
    upIconSortSmall,
    upIconSortUpSmall,
    upIconSpinnerMedium,
    upIconSplitMedium,
    upIconSubscriptions,
    upIconSyncMedium,
    upIconTakePhotoMedium,
    upIconTasksLarge,
    upIconTasksMedium,
    upIconTemplate,
    upIconTrailingArrowSmall,
    upIconTrailingIcon,
    upIconUpLogoName,
    upIconUpLogoShape,
    upIconUpLogoTagline,
    upIconUploadMedium,
    upIconUserMedium,
    upIconUserSmall,
    upIconVatExemptMedium,
    upIconVerticalDotsMedium,
    upIconWarningIcon,
    upIconZoomInDisabledMedium,
    upIconZoomInMedium,
    upIconZoomOutMedium,
    upIconAd,
    upIconAe,
    upIconAf,
    upIconAg,
    upIconAi,
    upIconAl,
    upIconAm,
    upIconAo,
    upIconAr,
    upIconAs,
    upIconAt,
    upIconAu,
    upIconAw,
    upIconAx,
    upIconAz,
    upIconBa,
    upIconBb,
    upIconBd,
    upIconBe,
    upIconBf,
    upIconBg,
    upIconBh,
    upIconBi,
    upIconBj,
    upIconBm,
    upIconBn,
    upIconBo,
    upIconBr,
    upIconBs,
    upIconBt,
    upIconBw,
    upIconBy,
    upIconBz,
    upIconCa,
    upIconCc,
    upIconCd,
    upIconCf,
    upIconCg,
    upIconCh,
    upIconCi,
    upIconCk,
    upIconCl,
    upIconCm,
    upIconCn,
    upIconCo,
    upIconCr,
    upIconCu,
    upIconCv,
    upIconCx,
    upIconCy,
    upIconCz,
    upIconDe,
    upIconDj,
    upIconDk,
    upIconDm,
    upIconDo,
    upIconDz,
    upIconEc,
    upIconEe,
    upIconEg,
    upIconEh,
    upIconEr,
    upIconEs,
    upIconEt,
    upIconFi,
    upIconFj,
    upIconFk,
    upIconFm,
    upIconFo,
    upIconFr,
    upIconGa,
    upIconGb,
    upIconGd,
    upIconGe,
    upIconGg,
    upIconGh,
    upIconGi,
    upIconGl,
    upIconGm,
    upIconGn,
    upIconGq,
    upIconGr,
    upIconGt,
    upIconGu,
    upIconGw,
    upIconGy,
    upIconHk,
    upIconHn,
    upIconHr,
    upIconHt,
    upIconHu,
    upIconId,
    upIconIe,
    upIconIl,
    upIconIm,
    upIconIn,
    upIconIo,
    upIconIq,
    upIconIr,
    upIconIs,
    upIconIt,
    upIconJe,
    upIconJm,
    upIconJo,
    upIconJp,
    upIconKe,
    upIconKg,
    upIconKh,
    upIconKi,
    upIconKm,
    upIconKn,
    upIconKp,
    upIconKw,
    upIconKy,
    upIconKz,
    upIconLa,
    upIconLb,
    upIconLc,
    upIconLi,
    upIconLk,
    upIconLr,
    upIconLs,
    upIconLt,
    upIconLu,
    upIconLv,
    upIconLy,
    upIconMa,
    upIconMc,
    upIconMd,
    upIconMe,
    upIconMf,
    upIconMg,
    upIconMh,
    upIconMk,
    upIconMl,
    upIconMm,
    upIconMn,
    upIconMo,
    upIconMp,
    upIconMq,
    upIconMr,
    upIconMs,
    upIconMt,
    upIconMu,
    upIconMv,
    upIconMw,
    upIconMx,
    upIconMy,
    upIconMz,
    upIconNa,
    upIconNe,
    upIconNf,
    upIconNg,
    upIconNi,
    upIconNl,
    upIconNo,
    upIconNp,
    upIconNr,
    upIconNu,
    upIconNz,
    upIconOm,
    upIconPa,
    upIconPe,
    upIconPf,
    upIconPg,
    upIconPh,
    upIconPk,
    upIconPl,
    upIconPn,
    upIconPr,
    upIconPs,
    upIconPt,
    upIconPw,
    upIconPy,
    upIconQa,
    upIconRo,
    upIconRs,
    upIconRu,
    upIconRw,
    upIconSa,
    upIconSb,
    upIconSc,
    upIconSd,
    upIconSe,
    upIconSg,
    upIconSi,
    upIconSk,
    upIconSl,
    upIconSm,
    upIconSn,
    upIconSo,
    upIconSr,
    upIconSs,
    upIconSt,
    upIconSv,
    upIconSy,
    upIconSz,
    upIconTc,
    upIconTd,
    upIconTg,
    upIconTh,
    upIconTj,
    upIconTk,
    upIconTl,
    upIconTm,
    upIconTn,
    upIconTo,
    upIconTr,
    upIconTt,
    upIconTv,
    upIconTw,
    upIconTz,
    upIconUa,
    upIconUg,
    upIconUs,
    upIconUy,
    upIconUz,
    upIconVa,
    upIconVc,
    upIconVe,
    upIconVg,
    upIconVi,
    upIconVn,
    upIconVu,
    upIconWs,
    upIconYe,
    upIconZa,
    upIconZm,
    upIconZw
];
