/* 🤖 this file was generated by svg-to-ts*/
export const upIconPlusMedium = {
    name: 'plus_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 11 10"><path fill="currentColor" fill-rule="evenodd" d="M6.833 1.333a1 1 0 10-2 0v2.334h-3a1 1 0 000 2h3v3a1 1 0 102 0v-3h2.334a1 1 0 000-2H6.833V1.333z" clip-rule="evenodd"/></svg>`
};
