/* 🤖 this file was generated by svg-to-ts*/
export const upIconInviteMedium = {
    name: 'invite_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M3 7.959a2 2 0 012-2h14a2 2 0 012 2v4a1 1 0 01-2 0V9.276l-6.35 5.442a1 1 0 01-1.3 0L5 9.276v8.683h3a1 1 0 110 2H5a2 2 0 01-2-2v-10zm3.537 0L12 12.642l5.463-4.683H6.537zm10.756 7.293a1 1 0 011.414 0l3 2.999a1 1 0 010 1.415l-3 3a1 1 0 01-1.414-1.414l1.293-1.293H12a1 1 0 010-2h6.586l-1.293-1.293a1 1 0 010-1.414z" clip-rule="evenodd"/></svg>`
};
