/* 🤖 this file was generated by svg-to-ts*/
export const upIconMw = {
    name: 'mw',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#MW_svg__clip0)"><path fill="#D80027" d="M0 24c0 2.936.528 5.748 1.493 8.348L24 33.39l22.507-1.043A23.947 23.947 0 0048 24c0-2.936-.528-5.748-1.493-8.348L24 14.61 1.493 15.652A23.95 23.95 0 000 24z"/><path fill="#000" d="M24 0C13.68 0 4.882 6.513 1.491 15.652h45.015C43.115 6.513 34.318 0 23.999 0z"/><path fill="#496E2D" d="M46.507 32.348H1.492C4.883 41.487 13.68 48 24 48c10.32 0 19.116-6.513 22.508-15.652z"/><path fill="#D80027" d="M31.174 11.478L28.243 10.1l1.56-2.839-3.182.609-.403-3.216L24 7.02l-2.216-2.365-.404 3.216-3.182-.609 1.56 2.839-2.93 1.378h14.346z"/></g><defs><clipPath id="MW_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
