/* 🤖 this file was generated by svg-to-ts*/
export const upIconBh = {
    name: 'bh',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#BH_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#D80027" d="M24 0c-4.817 0-9.3 1.42-13.06 3.862L17.114 8l-7.722 4 7.722 4-7.722 4 7.722 4-7.722 4 7.722 4-7.722 4 7.722 4-6.173 4.138A23.885 23.885 0 0024 48c13.255 0 24-10.745 24-24S37.255 0 24 0z"/></g><defs><clipPath id="BH_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
