/* 🤖 this file was generated by svg-to-ts*/
export const upIconLastPageMedium = {
    name: 'last_page_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M12 1.959a1 1 0 10-2 0v10a1 1 0 002 0v-10zM6.707 6.293l-.002-.003-4.998-4.997A1 1 0 00.293 2.707L4.586 7 .293 11.293a1 1 0 101.414 1.414l5-5a1 1 0 000-1.414z" clip-rule="evenodd"/></svg>`
};
