/* 🤖 this file was generated by svg-to-ts*/
export const upIconConfigMedium = {
    name: 'config_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M10.485 7.693L8.66 5.867a4.105 4.105 0 11-3.751 3.751l1.825 1.826a2.652 2.652 0 103.751-3.751zm-2.411 2.411L5.126 7.157l-.012-.012a.947.947 0 00-1.54.25 6 6 0 007.025 8.348l5.337 5.337a3 3 0 104.243-4.242l-5.37-5.37a6 6 0 00-8.373-6.935.947.947 0 00-.25 1.54l.012.012 2.947 2.948a.758.758 0 01-1.071 1.071zm5.84 3.298l4.85 4.85a1 1 0 11-1.414 1.414l-4.84-4.84a6.034 6.034 0 001.405-1.424z" clip-rule="evenodd"/></svg>`
};
