/* 🤖 this file was generated by svg-to-ts*/
export const upIconGoToMedium = {
    name: 'go_to_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" d="M14 3.959a1 1 0 100 2h3.586l-5.793 5.793a1 1 0 001.414 1.414L19 7.373v3.586a1 1 0 002 0v-6a1 1 0 00-1-1h-6z"/><path fill="currentColor" d="M4 5.959a1 1 0 00-1 1v14a1 1 0 001 1h14a1 1 0 001-1v-5a1 1 0 10-2 0v4H5v-12h4a1 1 0 100-2H4z"/></svg>`
};
