/* 🤖 this file was generated by svg-to-ts*/
export const upIconCompanyMedium = {
    name: 'company_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M4 3.5A1.5 1.5 0 015.5 2h13A1.5 1.5 0 0120 3.5v18a1.5 1.5 0 01-1.5 1.5h-13A1.5 1.5 0 014 21.5v-18zM6 4v17h7v-4.8c0-.11.09-.2.2-.2h2.6c.11 0 .2.09.2.2V21h2V4H6zm2 2.2c0-.11.09-.2.2-.2h2.6c.11 0 .2.09.2.2v2.6a.2.2 0 01-.2.2H8.2a.2.2 0 01-.2-.2V6.2zm5.2-.2a.2.2 0 00-.2.2v2.6c0 .11.09.2.2.2h2.6a.2.2 0 00.2-.2V6.2a.2.2 0 00-.2-.2h-2.6zM8 11.2c0-.11.09-.2.2-.2h2.6c.11 0 .2.09.2.2v2.6a.2.2 0 01-.2.2H8.2a.2.2 0 01-.2-.2v-2.6zm.2 4.8a.2.2 0 00-.2.2v2.6c0 .11.09.2.2.2h2.6a.2.2 0 00.2-.2v-2.6a.2.2 0 00-.2-.2H8.2zm4.8-4.8c0-.11.09-.2.2-.2h2.6c.11 0 .2.09.2.2v2.6a.2.2 0 01-.2.2h-2.6a.2.2 0 01-.2-.2v-2.6z" clip-rule="evenodd"/></svg>`
};
