/* 🤖 this file was generated by svg-to-ts*/
export const upIconNetworkMedium = {
    name: 'network_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M16 6a2 2 0 104 0 2 2 0 00-4 0zm2-4a4 4 0 00-3.99 4.276l-4.652 1.55A3.998 3.998 0 006 6a4 4 0 103.99 3.724l4.652-1.55a4.021 4.021 0 001.184 1.184l-1.55 4.651a3.982 3.982 0 00-2.308.544l-2.522-2.521a4.02 4.02 0 01-1.414 1.414l2.522 2.522a4 4 0 105.62-1.326l1.55-4.651A4 4 0 1018 2zM6 12a2 2 0 110-4 2 2 0 010 4zm8 8a2 2 0 110-4 2 2 0 010 4z" clip-rule="evenodd"/></svg>`
};
