/* 🤖 this file was generated by svg-to-ts*/
export const upIconCleanUpMedium = {
    name: 'clean_up_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M9 5.959a3 3 0 116 0v7a1 1 0 01-1 1h-4a1 1 0 01-1-1v-7zm3-1a1 1 0 00-1 1v6h2v-6a1 1 0 00-1-1z" clip-rule="evenodd"/><path fill="currentColor" fill-rule="evenodd" d="M5 12.959a1 1 0 011-1h12a1 1 0 011 1v3a1 1 0 01-1 1H6a1 1 0 01-1-1v-3zm2 1v1h10v-1H7z" clip-rule="evenodd"/><path fill="currentColor" fill-rule="evenodd" d="M5.051 15.643A1 1 0 016 14.959h12a1 1 0 01.949.684l1.56 4.683a2 2 0 01-1.896 2.633H5.386a2 2 0 01-1.897-2.633l1.561-4.683zm1.67 1.316l-1.334 4h13.226l-1.334-4H6.721z" clip-rule="evenodd"/><path fill="currentColor" d="M8 18.959a1 1 0 112 0v3H8v-3zM11 18.959a1 1 0 112 0v3h-2v-3zM14 18.959a1 1 0 112 0v3h-2v-3z"/></svg>`
};
