/* 🤖 this file was generated by svg-to-ts*/
export const upIconSearchMedium = {
    name: 'search_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M14 10a4 4 0 11-8 0 4 4 0 018 0zm-.287 4.713a6 6 0 111.342-1.48c.023.019.045.039.066.06l4.243 4.242a1 1 0 01-1.414 1.415l-4.237-4.237z" clip-rule="evenodd"/></svg>`
};
