/* 🤖 this file was generated by svg-to-ts*/
export const upIconArchiveMedium = {
    name: 'archive_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M20 6H4v2h16V6zM2 8a2 2 0 002 2v8a2 2 0 002 2h12a2 2 0 002-2v-8a2 2 0 002-2V6a2 2 0 00-2-2H4a2 2 0 00-2 2v2zm4 2h12v8H6v-8zm3 2a1 1 0 100 2h6a1 1 0 100-2H9z" clip-rule="evenodd"/></svg>`
};
