/* 🤖 this file was generated by svg-to-ts*/
export const upIconAccountsReceivableLarge = {
    name: 'accounts_receivable_large',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 32 32"><path fill="currentColor" fill-rule="evenodd" d="M9 3a2 2 0 00-2 2v4a1 1 0 002 0V5h7.586L23 11.414V27H9v-2a1 1 0 10-2 0v2a2 2 0 002 2h14a2 2 0 002-2V11.414A2 2 0 0024.414 10L18 3.586A2 2 0 0016.586 3H9zm9 13a1 1 0 110 2H7.08l2.294 2.293a1 1 0 11-1.415 1.414l-3.998-3.999h-.002a.997.997 0 010-1.415l.002-.001 3.998-4a1 1 0 011.415 1.415L7.08 16H18z" clip-rule="evenodd"/></svg>`
};
