/* 🤖 this file was generated by svg-to-ts*/
export const upIconDocumentLinkMedium = {
    name: 'document_link_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M7 2a2 2 0 00-2 2v4a1 1 0 002 0V4h5.586L17 8.414V20h-5a1 1 0 100 2h5a2 2 0 002-2V8.414A2 2 0 0018.414 7L14 2.586A2 2 0 0012.586 2H7zm-.707 13.121a1 1 0 101.414 1.415l3.586-3.586a1 1 0 00-1.414-1.414L6.293 15.12zm6.75-5.164a2.182 2.182 0 00-3.086 0l-1.25 1.25a1 1 0 01-1.414-1.414l1.25-1.25a4.182 4.182 0 115.914 5.914l-1.25 1.25a1 1 0 01-1.414-1.414l1.25-1.25a2.182 2.182 0 000-3.086zm-5 8.086a2.182 2.182 0 01-3.086-3.086l1.25-1.25a1 1 0 10-1.414-1.414l-1.25 1.25a4.182 4.182 0 105.914 5.914l1.25-1.25a1 1 0 00-1.414-1.414l-1.25 1.25z" clip-rule="evenodd"/></svg>`
};
