/* 🤖 this file was generated by svg-to-ts*/
export const upIconSi = {
    name: 'si',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#SI_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#0052B4" d="M46.507 15.652H20.87v-6.26H8.348v6.26H1.493A23.948 23.948 0 000 24c0 2.936.528 5.748 1.493 8.348L24 34.435l22.507-2.087A23.948 23.948 0 0048 24c0-2.936-.528-5.748-1.493-8.348z"/><path fill="#D80027" d="M24.001 48c10.32 0 19.116-6.513 22.507-15.652H1.494C4.884 41.487 13.682 48 24 48z"/><path fill="#F0F0F0" d="M8.348 15.652v2.087c0 4.793 6.26 6.261 6.26 6.261s6.262-1.468 6.262-6.26v-2.088l-2.087 2.087-4.174-3.13-4.174 3.13-2.087-2.087z"/></g><defs><clipPath id="SI_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
