/* 🤖 this file was generated by svg-to-ts*/
export const upIconSplitMedium = {
    name: 'split_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M6 4.959a2 2 0 100 4 2 2 0 000-4zM9.446 8.99a4 4 0 10-1.414 1.414l2.574 2.574-2.548 2.549a4 4 0 101.404 1.425L20.706 5.707a1 1 0 00-1.414-1.414l-7.272 7.272-2.575-2.574zM6 16.959a2 2 0 100 4 2 2 0 000-4zm7.793-2.166a1 1 0 011.414 0l5.5 5.5a1 1 0 01-1.414 1.414l-5.5-5.5a1 1 0 010-1.414z" clip-rule="evenodd"/></svg>`
};
