/* 🤖 this file was generated by svg-to-ts*/
export const upIconCh = {
    name: 'ch',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#D80027" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#F0F0F0" d="M36.523 19.826h-8.348v-8.348h-8.348v8.348H11.48v8.348h8.348v8.348h8.348v-8.348h8.348v-8.348z"/></svg>`
};
