/* 🤖 this file was generated by svg-to-ts*/
export const upIconAlertWarningMedium = {
    name: 'alert_warning_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M12 4a8 8 0 100 16 8 8 0 000-16zM2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12zm10-5a1 1 0 011 1v4.5a1 1 0 11-2 0V8a1 1 0 011-1zm1 9a1 1 0 10-2 0v.02a1 1 0 102 0V16z" clip-rule="evenodd"/></svg>`
};
