/* 🤖 this file was generated by svg-to-ts*/
export const upIconUploadMedium = {
    name: 'upload_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M7 2.959a2 2 0 00-2 2v3a1 1 0 102 0v-3h5.586L17 9.373V20.96h-7a1 1 0 100 2h7a2 2 0 002-2V9.373a2 2 0 00-.586-1.414L14 3.545a2 2 0 00-1.414-.586H7zM2.293 14.252a1 1 0 101.414 1.414L5 14.373v7.586a1 1 0 002 0v-7.586l1.293 1.293a1 1 0 001.414-1.414l-3-3a1 1 0 00-1.414 0l-3 3z" clip-rule="evenodd"/></svg>`
};
