/* 🤖 this file was generated by svg-to-ts*/
export const upIconCatalog = {
    name: 'catalog',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 21 20"><path fill="currentColor" d="M4 16a1 1 0 100-2 1 1 0 000 2z"/><path fill="currentColor" fill-rule="evenodd" d="M0 1a1 1 0 011-1h6a1 1 0 011 1v5.775l4.602-5.037a1 1 0 011.413-.064l4.43 4.047a1 1 0 01.063 1.413L14.063 12H19.2a1 1 0 011 1v6a1 1 0 01-1 1H1a1 1 0 01-1-1V1zm2 17V2h4v16H2zm6.581 0h9.62v-4h-5.966l-3.654 4zM8 15.67V9.74l5.404-5.915 2.953 2.698L8 15.671z" clip-rule="evenodd"/></svg>`
};
