/* 🤖 this file was generated by svg-to-ts*/
export const upIconFitToHeightMedium = {
    name: 'fit_to_height_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M5 2a3 3 0 00-3 3v14a3 3 0 003 3h14a3 3 0 003-3V5a3 3 0 00-3-3H5zM4 5a1 1 0 011-1h14a1 1 0 011 1v14a1 1 0 01-1 1H5a1 1 0 01-1-1V5zm3.247 5.659a1 1 0 01.095-1.412l3.989-3.49A.993.993 0 0112 5.5a.998.998 0 01.67.257l3.989 3.49a1 1 0 11-1.317 1.506L12 7.829l-3.341 2.924a1 1 0 01-1.412-.095zm.095 4.094a1 1 0 011.317-1.506L12 16.171l3.341-2.924a1 1 0 011.318 1.506l-3.99 3.49a.99.99 0 01-.672.257.997.997 0 01-.666-.257l-3.99-3.49z" clip-rule="evenodd"/></svg>`
};
