/* 🤖 this file was generated by svg-to-ts*/
export const upIconAlertErrorSmall = {
    name: 'alert_error_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 19"><path fill="currentColor" fill-rule="evenodd" d="M.33 10.853a2 2 0 010-1.789l3.5-7A2 2 0 015.617.96h8.764a2 2 0 011.789 1.105l3.5 7a2 2 0 010 1.79l-3.5 7a2 2 0 01-1.789 1.105H5.618a2 2 0 01-1.789-1.106l-3.5-7zM5.617 2.96l-3.5 7 3.5 7h8.764l3.5-7-3.5-7H5.618zm.675 3.293a1 1 0 011.414 0L10 8.545l2.293-2.293a1 1 0 011.414 1.414l-2.293 2.293 2.293 2.293a1 1 0 01-1.414 1.414L10 11.373l-2.293 2.293a1 1 0 01-1.414-1.414l2.293-2.293-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"/></svg>`
};
