/* 🤖 this file was generated by svg-to-ts*/
export const upIconCheckMarkMedium = {
    name: 'check_mark_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M13.138 4.195c.26.26.26.683 0 .943l-5.333 5.333a.667.667 0 01-.943 0l-2-2a.667.667 0 11.943-.942l1.528 1.528 4.862-4.862c.26-.26.683-.26.943 0z" clip-rule="evenodd"/></svg>`
};
