/* 🤖 this file was generated by svg-to-ts*/
export const upIconDocumentAltMedium = {
    name: 'document_alt_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M5 4.959a2 2 0 012-2h5.586A2 2 0 0114 3.545l4.414 4.414A2 2 0 0119 9.373V20.96a2 2 0 01-2 2H7a2 2 0 01-2-2v-16zm7.586 0H7v16h10V9.373L12.586 4.96z" clip-rule="evenodd"/></svg>`
};
