/* 🤖 this file was generated by svg-to-ts*/
export const upIconFitToWidthMedium = {
    name: 'fit_to_width_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M5 2a3 3 0 00-3 3v14a3 3 0 003 3h14a3 3 0 003-3V5a3 3 0 00-3-3H5zM4 5a1 1 0 011-1h14a1 1 0 011 1v14a1 1 0 01-1 1H5a1 1 0 01-1-1V5zm6.707 2.793a1 1 0 00-1.414 0l-3.5 3.5a1 1 0 000 1.414l3.5 3.5a1 1 0 001.414-1.414L7.914 12l2.793-2.793a1 1 0 000-1.414zm2.586 0a1 1 0 011.414 0l3.5 3.5a1 1 0 010 1.414l-3.5 3.5a1 1 0 01-1.414-1.414L16.086 12l-2.793-2.793a1 1 0 010-1.414z" clip-rule="evenodd"/></svg>`
};
