/* 🤖 this file was generated by svg-to-ts*/
export const upIconAmountMoreThan30DMedium = {
    name: 'amount_more_than_30_d_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M7 4a2 2 0 012-2h5.586A2 2 0 0116 2.584l4.414 4.414A2 2 0 0121 8.413V20a2 2 0 01-2 2h-2v-2h2V8.413L14.586 4H9v2.009l-2 .007V4zm0 5a1 1 0 10-2 0v1H4a2 2 0 00-2 2V19.998a2 2 0 002 2h9a2 2 0 002-2v-8a2 2 0 00-2-2h-1V9a1 1 0 10-2 0v1H7V9zm6 4.817H4V20h9v-6.182z" clip-rule="evenodd"/></svg>`
};
