/* 🤖 this file was generated by svg-to-ts*/
export const upIconArrowLeftMedium = {
    name: 'arrow_left_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M19 13a1 1 0 100-2H7.414l4.293-4.293a1 1 0 10-1.414-1.414l-6 6a1 1 0 000 1.414l6 6a1 1 0 001.414-1.414L7.414 13H19z" clip-rule="evenodd"/></svg>`
};
