/* 🤖 this file was generated by svg-to-ts*/
export const upIconMr = {
    name: 'mr',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#496E2D" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#FFDA44" d="M24 27.727a8.35 8.35 0 01-8.154-6.56 8.348 8.348 0 1016.307 0A8.35 8.35 0 0124 27.727z"/><path fill="#FFDA44" d="M24 16.696l.776 2.391h2.515l-2.034 1.478.777 2.391-2.035-1.477-2.034 1.477.777-2.39-2.034-1.479h2.514L24 16.696z"/></svg>`
};
