/* 🤖 this file was generated by svg-to-ts*/
export const upIconTasksLarge = {
    name: 'tasks_large',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 32 32"><path fill="currentColor" fill-rule="evenodd" d="M14 3h4c1.306 0 2.418.835 2.83 2H23a2 2 0 012 2v18a2 2 0 01-2 2H9a2 2 0 01-2-2V7a2 2 0 012-2h2.17A3.001 3.001 0 0114 3zm4 6a3.001 3.001 0 002.83-2H23v18H9V7h2.17A3.001 3.001 0 0014 9h4zm-4-4a1 1 0 100 2h4a1 1 0 100-2h-4zm-2 6a1 1 0 100 2h8a1 1 0 100-2h-8zm-1 5a1 1 0 011-1h8a1 1 0 110 2h-8a1 1 0 01-1-1zm1 3a1 1 0 100 2h8a1 1 0 100-2h-8z" clip-rule="evenodd"/></svg>`
};
