/* 🤖 this file was generated by svg-to-ts*/
export const upIconProductCatalogMedium = {
    name: 'product_catalog_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" d="M6 19a1 1 0 100-2 1 1 0 000 2z"/><path fill="currentColor" fill-rule="evenodd" d="M2 4a1 1 0 011-1h6a1 1 0 011 1v5.775l4.602-5.037a1 1 0 011.413-.064l4.43 4.047a1 1 0 01.063 1.413L16.063 15H21.2a1 1 0 011 1v6a1 1 0 01-1 1H3a1 1 0 01-1-1V4zm2 17V5h4v16H4zm6.581 0h9.62v-4h-5.966l-3.654 4zM10 18.67v-5.93l5.404-5.915 2.953 2.698L10 18.671z" clip-rule="evenodd"/></svg>`
};
