/* 🤖 this file was generated by svg-to-ts*/
export const upIconDiscount = {
    name: 'discount',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M9 8.459a2.5 2.5 0 100 5 2.5 2.5 0 000-5zm-.5 2.5a.5.5 0 111 0 .5.5 0 01-1 0zM15 14.459a2.5 2.5 0 100 5 2.5 2.5 0 000-5zm-.5 2.5a.5.5 0 111 0 .5.5 0 01-1 0z" clip-rule="evenodd"/><path fill="currentColor" d="M7.293 18.707a1 1 0 010-1.414l8-8a1 1 0 111.414 1.414l-8 8a1 1 0 01-1.414 0z"/><path fill="currentColor" fill-rule="evenodd" d="M3 9.724V21a2 2 0 002 2h14a2 2 0 002-2V9.724a2 2 0 00-.464-1.28L16.6 3.72A2 2 0 0015.063 3H8.937a2 2 0 00-1.537.72L3.464 8.444A2 2 0 003 9.724zM5 21V9.724L8.937 5h6.126L19 9.724V21H5z" clip-rule="evenodd"/></svg>`
};
