/* 🤖 this file was generated by svg-to-ts*/
export const upIconPs = {
    name: 'ps',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#PS_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#000" d="M14.61 15.652h31.898C43.117 6.513 34.32 0 24 0A23.922 23.922 0 007.03 7.03l7.578 8.622z"/><path fill="#6DA544" d="M14.61 32.348h31.898C43.117 41.487 34.32 48 24 48a23.922 23.922 0 01-16.97-7.03l7.578-8.622z"/><path fill="#D80027" d="M7.029 7.03c-9.373 9.372-9.373 24.568 0 33.94L23.999 24 7.03 7.03z"/></g><defs><clipPath id="PS_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
