/* 🤖 this file was generated by svg-to-ts*/
export const upIconAccountsPayableLarge = {
    name: 'accounts_payable_large',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 32 32"><path fill="currentColor" fill-rule="evenodd" d="M9 3a2 2 0 00-2 2v7a1 1 0 102 0V5h7.586L23 11.414V27H9v-5a1 1 0 10-2 0v5a2 2 0 002 2h14a2 2 0 002-2V11.414A2 2 0 0024.414 10L18 3.586A2 2 0 0016.586 3H9zM4 16a1 1 0 100 2h10.92l-2.294 2.293a1 1 0 001.415 1.414l3.998-3.999h.002a1.002 1.002 0 000-1.415l-.002-.002-3.998-3.998a1 1 0 00-1.415 1.414L14.92 16H4z" clip-rule="evenodd"/></svg>`
};
