/* 🤖 this file was generated by svg-to-ts*/
export const upIconAlertWarningSmall = {
    name: 'alert_warning_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M8 1.75a6.25 6.25 0 100 12.5 6.25 6.25 0 000-12.5zM.25 8a7.75 7.75 0 1115.5 0A7.75 7.75 0 01.25 8zM8 4.25a.75.75 0 01.75.75v3a.75.75 0 01-1.5 0V5A.75.75 0 018 4.25zM8.75 11a.75.75 0 00-1.5 0v.02a.75.75 0 001.5 0V11z" clip-rule="evenodd"/></svg>`
};
