/* 🤖 this file was generated by svg-to-ts*/
export const upIconFirstPageLarge = {
    name: 'first_page_large',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 32 32"><path fill="currentColor" fill-rule="evenodd" d="M2 1.959a1 1 0 00-2 0v10a1 1 0 002 0v-10zm8.293-.666L5.296 6.29l-.003.003a.997.997 0 000 1.414l.003.003 4.997 4.997a1 1 0 101.414-1.414L7.414 7l4.293-4.293a1 1 0 00-1.414-1.414z" clip-rule="evenodd"/></svg>`
};
