/* 🤖 this file was generated by svg-to-ts*/
export const upIconCalendarSmall = {
    name: 'calendar_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M6.75 1a.75.75 0 00-1.5 0v.75H4.5A2.75 2.75 0 001.75 4.5v7a2.75 2.75 0 002.75 2.75h7a2.75 2.75 0 002.75-2.75v-7a2.75 2.75 0 00-2.75-2.75h-.75V1a.75.75 0 00-1.5 0v.75h-2.5V1zm-1.5 2.25V4a.75.75 0 001.5 0v-.75h2.5V4a.75.75 0 001.5 0v-.75h.75c.69 0 1.25.56 1.25 1.25v1.75h-9.5V4.5c0-.69.56-1.25 1.25-1.25h.75zm-2 4.5v3.75c0 .69.56 1.25 1.25 1.25h7c.69 0 1.25-.56 1.25-1.25V7.75h-9.5z" clip-rule="evenodd"/></svg>`
};
