/* 🤖 this file was generated by svg-to-ts*/
export const upIconSortSmall = {
    name: 'sort_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 16"><path fill="currentColor" fill-rule="evenodd" d="M5.707.293a1 1 0 00-1.414 0l-4 4a1 1 0 001.414 1.414L5 2.414l3.293 3.293a1 1 0 001.414-1.414l-4-4zm-4 10a1 1 0 10-1.414 1.414l4 4a1 1 0 001.414 0l4-4a1 1 0 00-1.414-1.414L5 13.586l-3.293-3.293z" clip-rule="evenodd"/></svg>`
};
