/* 🤖 this file was generated by svg-to-ts*/
export const upIconDj = {
    name: 'dj',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#DJ_svg__clip0)"><path fill="#338AF3" d="M21.913 26.087S7.043 7.027 7.03 7.029A23.925 23.925 0 0124 0c13.255 0 24 10.745 24 24l-26.087 2.087z"/><path fill="#6DA544" d="M21.913 24S7.043 40.974 7.03 40.97A23.925 23.925 0 0024 48c13.255 0 24-10.745 24-24H21.913z"/><path fill="#F0F0F0" d="M7.029 7.03c-9.373 9.372-9.373 24.568 0 33.94L23.999 24 7.03 7.03z"/><path fill="#D80027" d="M9.713 17.74l1.554 4.782h5.03l-4.07 2.956 1.555 4.783-4.069-2.956-4.068 2.956 1.554-4.783-4.069-2.956h5.03l1.553-4.783z"/></g><defs><clipPath id="DJ_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
