/* 🤖 this file was generated by svg-to-ts*/
export const upIconDoneMedium = {
    name: 'done_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="#312B78" fill-rule="evenodd" d="M14.757 7H7v10h10v-3.757l2-2V17a2 2 0 01-2 2H7a2 2 0 01-2-2V7a2 2 0 012-2h9.757l-2 2z" clip-rule="evenodd"/><path fill="#50E2D1" fill-rule="evenodd" d="M19.707 6.293a1 1 0 010 1.414l-7 7a1 1 0 01-1.414 0l-2-2a1 1 0 111.414-1.414L12 12.586l6.293-6.293a1 1 0 011.414 0z" clip-rule="evenodd"/></svg>`
};
