/* 🤖 this file was generated by svg-to-ts*/
export const upIconCancelChangesMedium = {
    name: 'cancel_changes_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M5.707 5.293a1 1 0 00-1.414 1.414l14 14a1 1 0 001.414-1.414l-14-14zm-.414 10l2.379-2.379 1.414 1.414L7 16.414V18h1.586l2.086-2.086 1.414 1.414-2.379 2.38A1 1 0 019 20H6a1 1 0 01-1-1v-3a1 1 0 01.293-.707zM17.586 9l-2.672 2.672 1.414 1.414 3.38-3.379a1 1 0 000-1.414l-3-3a1 1 0 00-1.415 0l-3.379 3.379 1.414 1.414L16 7.414 17.586 9z" clip-rule="evenodd"/></svg>`
};
