/* 🤖 this file was generated by svg-to-ts*/
export const upIconAmountTotalYenMedium = {
    name: 'amount_total_yen_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" d="M12 20.459V19H9v-1.541h3v-1.5H9l3-5h-2l-2 3.5-2-3.5H4l3 5H4v1.5h3V19H4v1.459h3v1.5h2v-1.5h3z"/><path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M15 21.959h4a1 1 0 001-1V9.373a1 1 0 00-.293-.707l-4.414-4.414a1 1 0 00-.707-.293H9a1 1 0 00-1 1v3"/></svg>`
};
