/* 🤖 this file was generated by svg-to-ts*/
export const upIconAddSmall = {
    name: 'add_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 16"><path fill="currentColor" fill-rule="evenodd" d="M9.833 4.333a1 1 0 10-2 0v2.334h-3a1 1 0 000 2h3v3a1 1 0 002 0v-3h2.334a1 1 0 100-2H9.833V4.333z" clip-rule="evenodd"/></svg>`
};
