/* 🤖 this file was generated by svg-to-ts*/
export const upIconSpinnerMedium = {
    name: 'spinner_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" style="margin:auto" display="block" preserveAspectRatio="xMidYMid" viewBox="0 0 100 100"><circle cx="50" cy="50" r="24" fill="none" stroke="currentColor" stroke-dasharray="113.09733552923255 39.69911184307752" stroke-width="2"><animateTransform attributeName="transform" dur="1s" keyTimes="0;1" repeatCount="indefinite" type="rotate" values="0 50 50;360 50 50"/></circle></svg>`
};
