/* 🤖 this file was generated by svg-to-ts*/
export const upIconMoveToMedium = {
    name: 'move_to_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M2 6.959a2 2 0 012-2h4a1 1 0 01.707.293l1.707 1.707H20a2 2 0 012 2v10a2 2 0 01-2 2h-6.716l.837-.838c.339-.338.58-.737.722-1.162H20v-10H10a1 1 0 01-.707-.293L7.586 6.959H4v4.212a3.013 3.013 0 00-2 0V6.959zm.293 6.334a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L5.586 18l-3.293-3.293a1 1 0 010-1.414zm5 1.414a1 1 0 111.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L10.586 18l-3.293-3.293z" clip-rule="evenodd"/></svg>`
};
