/* 🤖 this file was generated by svg-to-ts*/
export const upIconDocument = {
    name: 'document',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M7 2.959a2 2 0 00-2 2v16a2 2 0 002 2h10a2 2 0 002-2V9.373a2 2 0 00-.586-1.414L14 3.545a2 2 0 00-1.414-.586H7zm0 2h5.586L17 9.373V20.96H7v-16zm2.5 11.5a1 1 0 100 2H12a1 1 0 000-2H9.5zm-1-2.5a1 1 0 011-1h5a1 1 0 110 2h-5a1 1 0 01-1-1zm1-4.5a1 1 0 000 2h4a1 1 0 000-2h-4z" clip-rule="evenodd"/><path fill="currentColor" fill-rule="evenodd" d="M7 2.959a2 2 0 00-2 2v16a2 2 0 002 2h10a2 2 0 002-2V9.373a2 2 0 00-.586-1.414L14 3.545a2 2 0 00-1.414-.586H7zm0 2h5.586L17 9.373V20.96H7v-16zm2.5 11.5a1 1 0 100 2H12a1 1 0 000-2H9.5zm-1-2.5a1 1 0 011-1h5a1 1 0 110 2h-5a1 1 0 01-1-1zm1-4.5a1 1 0 000 2h4a1 1 0 000-2h-4z" clip-rule="evenodd"/></svg>`
};
