/* 🤖 this file was generated by svg-to-ts*/
export const upIconIdeaMedium = {
    name: 'idea_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" d="M12 5.5a1 1 0 100 2 1 1 0 011 1 1 1 0 102 0 3 3 0 00-3-3z"/><path fill="currentColor" fill-rule="evenodd" d="M16 15.041v-1.376a6.5 6.5 0 10-8 0v1.376a1 1 0 001 1h6a1 1 0 001-1zm-1.232-2.952l-.768.6v1.352h-4V12.69l-.768-.6a4.5 4.5 0 115.536 0z" clip-rule="evenodd"/><path fill="currentColor" d="M10 20.041a1 1 0 000 2h4a1 1 0 100-2h-4zM8 18.041a1 1 0 011-1h6a1 1 0 010 2H9a1 1 0 01-1-1z"/></svg>`
};
