/* 🤖 this file was generated by svg-to-ts*/
export const upIconSd = {
    name: 'sd',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#SD_svg__clip0)"><path fill="#F0F0F0" d="M2.381 13.565A23.904 23.904 0 000 24c0 3.74.856 7.28 2.381 10.435L24 36.522l21.619-2.087A23.906 23.906 0 0048 24c0-3.74-.856-7.28-2.381-10.435L24 11.478 2.381 13.565z"/><path fill="#000" d="M2.383 34.435C6.265 42.463 14.486 48 24.001 48c9.515 0 17.736-5.537 21.617-13.565H2.383z"/><path fill="#D80027" d="M2.383 13.565h43.235C41.737 5.537 33.516 0 24.001 0S6.265 5.537 2.383 13.565z"/><path fill="#496E2D" d="M7.029 7.03c-9.373 9.372-9.373 24.568 0 33.94L23.999 24 7.03 7.03z"/></g><defs><clipPath id="SD_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
