/* 🤖 this file was generated by svg-to-ts*/
export const upIconVerticalDotsMedium = {
    name: 'vertical_dots_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M10 5.876a2 2 0 114 0 2 2 0 01-4 0zm0 7a2 2 0 114 0 2 2 0 01-4 0zm2 5a2 2 0 100 4 2 2 0 000-4z" clip-rule="evenodd"/></svg>`
};
