/* 🤖 this file was generated by svg-to-ts*/
export const upIconSessionsMedium = {
    name: 'sessions_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M9 2.959a1 1 0 011 1V5h4V3.959a1 1 0 112 0V5h3a2 2 0 012 2v2.474a8.967 8.967 0 00-2-1.003V7h-3v.959a9.03 9.03 0 00-1.976.218A1 1 0 0114 7.959V7h-4v.959a1 1 0 11-2 0V7H5v3.459h4.775a9.036 9.036 0 00-1.571 2H5V21h2.956c.367.729.83 1.401 1.373 2H5a2 2 0 01-2-2V7a2 2 0 012-2h3V3.959a1 1 0 011-1zm7 18a4 4 0 100-8 4 4 0 000 8zm0 2a6 6 0 100-12 6 6 0 000 12zm2.942-5.415a3 3 0 01-.82 1.536L16 16.96v-3a3 3 0 012.942 3.585z" clip-rule="evenodd"/></svg>`
};
