/* 🤖 this file was generated by svg-to-ts*/
export const upIconChevronDownMedium = {
    name: 'chevron_down_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M18.364 10.778a1 1 0 00-1.414-1.414L12 14.314l-4.95-4.95a1 1 0 10-1.414 1.414l5.657 5.657a1 1 0 001.414 0l5.657-5.657z" clip-rule="evenodd"/></svg>`
};
