/* 🤖 this file was generated by svg-to-ts*/
export const upIconJm = {
    name: 'jm',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#JM_svg__clip0)"><path fill="#FFDA44" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#6DA544" d="M38.612 4.961A23.892 23.892 0 0024 0 23.893 23.893 0 009.39 4.961L24 19.573 38.612 4.96z"/><path fill="#000" d="M4.961 9.388A23.893 23.893 0 000 24c0 5.499 1.85 10.565 4.961 14.612L19.573 24 4.96 9.388z"/><path fill="#6DA544" d="M9.389 43.039A23.892 23.892 0 0024 48c5.5 0 10.565-1.85 14.612-4.961L24 28.427 9.39 43.04z"/><path fill="#000" d="M43.04 38.611A23.892 23.892 0 0048 24c0-5.499-1.85-10.565-4.96-14.612L28.427 24l14.611 14.611z"/></g><defs><clipPath id="JM_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
