/* 🤖 this file was generated by svg-to-ts*/
export const upIconSaveMedium = {
    name: 'save_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M3 5a2 2 0 012-2h10.172a3 3 0 012.12.879l2.83 2.828A3 3 0 0121 8.828V19a2 2 0 01-2 2H5a2 2 0 01-2-2V5zm6 14h6v-5H9v5zm8 0v-5.5a1.5 1.5 0 00-1.5-1.5h-7A1.5 1.5 0 007 13.5V19H5V5h2v2.5A1.5 1.5 0 008.5 9h5A1.5 1.5 0 0015 7.5V5h.172a1 1 0 01.707.293l2.828 2.828a1 1 0 01.293.707V19h-2zM9 5h4v2H9V5z" clip-rule="evenodd"/></svg>`
};
