/* 🤖 this file was generated by svg-to-ts*/
export const upIconChevronLeftSmall = {
    name: 'chevron_left_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M8.47 11.53a.75.75 0 101.06-1.06L7.06 8l2.47-2.47a.75.75 0 00-1.06-1.06l-3 3a.75.75 0 000 1.06l3 3z" clip-rule="evenodd"/></svg>`
};
