/* 🤖 this file was generated by svg-to-ts*/
export const upIconSyncMedium = {
    name: 'sync_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M22.707 11.67a1 1 0 010 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 011.414-1.415L18 12.962v-.085A6 6 0 008.572 7.95a1 1 0 01-1.144-1.64A8 8 0 0120 12.877v.085l1.293-1.293a1 1 0 011.414 0zM1.293 14.083a1 1 0 010-1.415l3-3a1 1 0 011.414 0l3 3a1 1 0 11-1.414 1.415L6 12.79v.085a6 6 0 009.428 4.926 1 1 0 111.144 1.64A8 8 0 014 12.876v-.085l-1.293 1.293a1 1 0 01-1.414 0z" clip-rule="evenodd"/></svg>`
};
