/* 🤖 this file was generated by svg-to-ts*/
export const upIconCountryPlaceholder = {
    name: 'country_placeholder',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20"><circle cx="10" cy="10" r="9.5" fill="#50E2D1" stroke="#50E2D1"/></svg>`
};
