/* 🤖 this file was generated by svg-to-ts*/
export const upIconId = {
    name: 'id',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#A2001D" d="M0 24C0 10.745 10.745 0 24 0s24 10.745 24 24"/></svg>`
};
