/* 🤖 this file was generated by svg-to-ts*/
export const upIconIq = {
    name: 'iq',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#IQ_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#A2001D" d="M24 0C13.681 0 4.884 6.513 1.493 15.652h45.014C43.117 6.513 34.32 0 24 0z"/><path fill="#000" d="M24 48c10.32 0 19.116-6.513 22.507-15.652H1.493C4.883 41.487 13.68 48 24 48z"/><path fill="#496E2D" d="M18.26 22.435h-4.626a2.089 2.089 0 012.018-1.566v-3.13a5.223 5.223 0 00-5.217 5.217v2.609h7.826c.288 0 .522.234.522.522v1.043H8.348v3.13h13.565v-4.173a3.656 3.656 0 00-3.652-3.652zM26.088 27.13V17.74h-3.13v12.522h5.217v-3.13h-2.087zM36.521 27.13V17.74h-3.13v9.391h-1.044V24h-3.13v6.26h9.391v-3.13h-2.087z"/></g><defs><clipPath id="IQ_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
