/* 🤖 this file was generated by svg-to-ts*/
export const upIconZoomInDisabledMedium = {
    name: 'zoom_in_disabled_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M12 7A5 5 0 112 7a5 5 0 0110 0zm-.808 5.606a7 7 0 111.414-1.414l3.101 3.1a1 1 0 01-1.414 1.415l-3.1-3.1zM7 3.46a1 1 0 011 1v1.5h1.5a1 1 0 110 2H8v1.5a1 1 0 01-2 0v-1.5H4.5a1 1 0 110-2H6v-1.5a1 1 0 011-1z" clip-rule="evenodd"/><path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M1 14.586L14.435 1.151"/></svg>`
};
