/* 🤖 this file was generated by svg-to-ts*/
export const upIconCm = {
    name: 'cm',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#CM_svg__clip0)"><path fill="#D80027" d="M34.435 2.381A23.905 23.905 0 0024 0c-3.74 0-7.28.856-10.435 2.381L11.478 24l2.087 21.619A23.907 23.907 0 0024 48c3.74 0 7.28-.856 10.435-2.381L36.522 24 34.435 2.381z"/><path fill="#FFDA44" d="M24 15.652l2.072 6.377h6.705l-5.424 3.942 2.072 6.377L24 28.406l-5.425 3.942 2.072-6.377-5.424-3.942h6.705L24 15.652z"/><path fill="#496E2D" d="M13.565 2.382C5.537 6.264 0 14.485 0 24c0 9.515 5.537 17.736 13.565 21.618V2.382z"/><path fill="#FFDA44" d="M34.435 2.382v43.236C42.463 41.736 48 33.515 48 24c0-9.515-5.537-17.736-13.565-21.618z"/></g><defs><clipPath id="CM_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
