/* 🤖 this file was generated by svg-to-ts*/
export const upIconArrowRightMedium = {
    name: 'arrow_right_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M5 11.959a1 1 0 100 2h11.627l-4.334 4.334a1 1 0 001.414 1.414l5.997-5.997.003-.003a1.001 1.001 0 000-1.414l-.003-.003-5.997-5.997a1 1 0 10-1.414 1.414l4.252 4.252H5z" clip-rule="evenodd"/></svg>`
};
