/* 🤖 this file was generated by svg-to-ts*/
export const upIconExpandMedium = {
    name: 'expand_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M4 6.084a1 1 0 000 2h7a1 1 0 100-2H4zm17.707 7.623l-.005.005-4.995 4.995a1 1 0 01-1.414-1.414L18.586 14H4a1 1 0 110-2h14.586l-3.293-3.293a1 1 0 011.414-1.414l5 5a1 1 0 010 1.414zM3 19.084a1 1 0 011-1h7a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"/></svg>`
};
