/* 🤖 this file was generated by svg-to-ts*/
export const upIconSo = {
    name: 'so',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#338AF3" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#F0F0F0" d="M24 12.522l2.59 7.971h8.382L28.19 25.42l2.59 7.971-6.78-4.926-6.782 4.926 2.59-7.971-6.78-4.927h8.381L24 12.522z"/></svg>`
};
