/* 🤖 this file was generated by svg-to-ts*/
export const upIconPayMedium = {
    name: 'pay_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M4 4.541a2 2 0 00-2 2v11a2 2 0 002 2h4a1 1 0 100-2H4v-6h15v.5a1 1 0 102 0v-5.5a2 2 0 00-2-2H4zm15 4v-2H4v2h15zM6 14.5a1 1 0 011-1h5.5a1 1 0 110 2H7a1 1 0 01-1-1zm12.707.293a1 1 0 10-1.414 1.414l1.293 1.293H12a1 1 0 100 2h6.586l-1.293 1.293a1 1 0 001.414 1.414l3-3a1 1 0 000-1.414v-.001l-3-3z" clip-rule="evenodd"/></svg>`
};
