/* 🤖 this file was generated by svg-to-ts*/
export const upIconMultiMedium = {
    name: 'multi_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M6 7a2 2 0 012-2h12a2 2 0 012 2v8a2 2 0 01-2 2V7H6zM4 9a2 2 0 00-2 2v8a2 2 0 002 2h12a2 2 0 002-2v-8a2 2 0 00-2-2H4zm0 2h12v8H4v-8z" clip-rule="evenodd"/></svg>`
};
