/* 🤖 this file was generated by svg-to-ts*/
export const upIconAccountsPayableMedium = {
    name: 'accounts_payable_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M7 2a2 2 0 00-2 2v5a1 1 0 002 0V4h5.586L17 8.414V20H7v-3a1 1 0 10-2 0v3a2 2 0 002 2h10a2 2 0 002-2V8.414A2 2 0 0018.414 7L14 2.586A2 2 0 0012.586 2H7zm3.707 7.293a1 1 0 00-1.414 1.414L10.586 12H3a1 1 0 100 2h7.586l-1.293 1.293a1 1 0 101.414 1.414l3-3A.997.997 0 0014 13.01m-.294-.717l-2.999-3m3 3l.007.008-.008-.008zm.007.008a.996.996 0 01.21.317l-.21-.318zm.21.317a.996.996 0 01.076.374l-.076-.374z" clip-rule="evenodd"/></svg>`
};
