/* 🤖 this file was generated by svg-to-ts*/
export const upIconAttachmentMedium = {
    name: 'attachment_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M6.834 13.094a4.25 4.25 0 006.01 6.01l2.06-2.06a1 1 0 011.415 1.414l-2.06 2.06a6.25 6.25 0 01-8.84-8.838l3.36-3.36 1.413-1.414L11.96 5.14a4.5 4.5 0 116.364 6.364l-3.182 3.182-3.005 3.005a2.75 2.75 0 01-3.89-3.89l4.42-4.419a1 1 0 111.415 1.415l-4.42 4.419a.75.75 0 001.06 1.06l3.006-3.005 3.182-3.181a2.5 2.5 0 00-3.536-3.536L11.607 8.32l-1.415 1.414-3.358 3.359z" clip-rule="evenodd"/></svg>`
};
