/* 🤖 this file was generated by svg-to-ts*/
export const upIconEg = {
    name: 'eg',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#EG_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#D80027" d="M24 0C13.681 0 4.884 6.513 1.493 15.652h45.014C43.117 6.513 34.32 0 24 0z"/><path fill="#000" d="M24 48c10.32 0 19.116-6.513 22.507-15.652H1.493C4.883 41.487 13.68 48 24 48z"/><path fill="#FF9811" d="M32.348 21.391h-6.261a2.087 2.087 0 00-4.174 0h-6.261c0 1.153 1.004 2.087 2.156 2.087h-.07c0 1.153.935 2.087 2.088 2.087 0 1.153.934 2.087 2.087 2.087h4.174a2.087 2.087 0 002.087-2.087 2.087 2.087 0 002.087-2.087h-.07c1.153 0 2.157-.934 2.157-2.087z"/></g><defs><clipPath id="EG_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
