/* 🤖 this file was generated by svg-to-ts*/
export const upIconEditMedium = {
    name: 'edit_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M18.707 3.293a1 1 0 00-1.414 0l-8 8A1 1 0 009 12v3a1 1 0 001 1h3a1 1 0 00.707-.293l8-8a1 1 0 000-1.414l-3-3zM11 14v-1.586l7-7L19.586 7l-7 7H11zM6 4.959a2 2 0 00-2 2v12a2 2 0 002 2h12a2 2 0 002-2v-5a1 1 0 10-2 0v5H6v-12h5a1 1 0 100-2H6z" clip-rule="evenodd"/></svg>`
};
