/* 🤖 this file was generated by svg-to-ts*/
export const upIconDocumentNotLinkedMedium = {
    name: 'document_not_linked_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" d="M7 2.959a2 2 0 00-2 2v6a1 1 0 002 0v-6h5.586L17 9.373V20.96h-4a1 1 0 100 2h4a2 2 0 002-2V9.373a2 2 0 00-.586-1.414L14 3.545a2 2 0 00-1.414-.586H7z"/><path fill="currentColor" d="M2.293 16.252a1 1 0 011.414 0L5.5 18.045l1.793-1.793a1 1 0 111.414 1.414l-1.793 1.793 1.793 1.793a1 1 0 11-1.414 1.414L5.5 20.873l-1.793 1.793a1 1 0 01-1.414-1.414l1.793-1.793-1.793-1.793a1 1 0 010-1.414z"/></svg>`
};
