/* 🤖 this file was generated by svg-to-ts*/
export const upIconTo = {
    name: 'to',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#D80027" d="M15.65 12.522v-3.13h-3.13v3.13H9.39v3.13h3.13v3.13h3.13v-3.13h3.131v-3.13h-3.13z"/><path fill="#D80027" d="M24 0v24H0c0 13.255 10.745 24 24 24s24-10.745 24-24S37.255 0 24 0z"/></svg>`
};
