/* 🤖 this file was generated by svg-to-ts*/
export const upIconLeadingArrowSmall = {
    name: 'leading_arrow_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M12.667 8.667a.667.667 0 000-1.334H4.943l2.862-2.862a.667.667 0 00-.943-.942l-4 4a.667.667 0 000 .942l4 4a.667.667 0 00.943-.942L4.943 8.667h7.724z" clip-rule="evenodd"/></svg>`
};
