/* 🤖 this file was generated by svg-to-ts*/
export const upIconChevronUpSmall = {
    name: 'chevron_up_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M4.47 8.47a.75.75 0 001.06 1.06L8 7.06l2.47 2.47a.75.75 0 001.06-1.06l-3-3a.75.75 0 00-1.06 0l-3 3z" clip-rule="evenodd"/></svg>`
};
