/* 🤖 this file was generated by svg-to-ts*/
export const upIconFi = {
    name: 'fi',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#0052B4" d="M47.797 20.87H18.783V.57a23.838 23.838 0 00-6.261 2.348V20.87H.203a24.205 24.205 0 000 6.261h12.319v17.952a23.838 23.838 0 006.26 2.347V27.131h29.015a24.224 24.224 0 000-6.261z"/></svg>`
};
