/* 🤖 this file was generated by svg-to-ts*/
export const upIconTasksMedium = {
    name: 'tasks_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M13 2h-2a3.001 3.001 0 00-2.83 2H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V6a2 2 0 00-2-2h-1.17A3.001 3.001 0 0013 2zm2.83 4H17v12H7V6h1.17A3.001 3.001 0 0011 8h2a3.001 3.001 0 002.83-2zM11 4a1 1 0 100 2h2a1 1 0 100-2h-2zm-2 7a1 1 0 011-1h4a1 1 0 110 2h-4a1 1 0 01-1-1zm1 3a1 1 0 100 2h4a1 1 0 100-2h-4z" clip-rule="evenodd"/></svg>`
};
