/* 🤖 this file was generated by svg-to-ts*/
export const upIconBankAccountsMedium = {
    name: 'bank_accounts_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M4 6h16v2H4V6zm0 5v7h16v-7H4zM2 6a2 2 0 012-2h16a2 2 0 012 2v12a2 2 0 01-2 2H4a2 2 0 01-2-2V6zm4 9a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm10-1a1 1 0 100 2h1a1 1 0 100-2h-1z" clip-rule="evenodd"/></svg>`
};
