/* 🤖 this file was generated by svg-to-ts*/
export const upIconMarkAsAcceptMedium = {
    name: 'mark_as_accept_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="#312B78" fill-rule="evenodd" d="M5 4.959a2 2 0 012-2h5.586A2 2 0 0114 3.545l4.414 4.414A2 2 0 0119 9.373V20.96a2 2 0 01-2 2h-3a1 1 0 010-2h3V9.373L12.586 4.96H7v9a1 1 0 01-2 0v-9z" clip-rule="evenodd"/><path fill="#50E2D1" fill-rule="evenodd" d="M12.707 15.252a1 1 0 010 1.414l-6 6a1 1 0 01-1.414 0l-3-3a1 1 0 111.414-1.414L6 20.545l5.293-5.293a1 1 0 011.414 0z" clip-rule="evenodd"/></svg>`
};
