/* 🤖 this file was generated by svg-to-ts*/
export const upIconLc = {
    name: 'lc',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#338AF3" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#F3F3F3" d="M15.13 32.348h17.74L24 11.478l-8.87 20.87z"/><path fill="#333" d="M18.214 30.26l5.787-13.163 5.787 13.164H18.214z"/><path fill="#FFDA44" d="M15.13 32.348h17.74L24 24l-8.87 8.348z"/></svg>`
};
