/* 🤖 this file was generated by svg-to-ts*/
export const upIconTemplate = {
    name: 'template',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" d="M11 17a1 1 0 011-1h5a1 1 0 110 2h-5a1 1 0 01-1-1zM12 12a1 1 0 100 2h5a1 1 0 100-2h-5z"/><path fill="currentColor" fill-rule="evenodd" d="M4 22a2 2 0 01-2-2V6a2 2 0 012-2h16a2 2 0 012 2v14a2 2 0 01-2 2H4zM20 6H4v2h16V6zM4 20V10h3v10H4zm5 0V10h11v10H9z" clip-rule="evenodd"/></svg>`
};
