/* 🤖 this file was generated by svg-to-ts*/
export const upIconCollapseMedium = {
    name: 'collapse_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M13 6.084a1 1 0 100 2h7a1 1 0 000-2h-7zM8.707 18.707a1 1 0 01-1.414 0l-5-4.999a.998.998 0 010-1.415l.004-.004 4.996-4.996a1 1 0 111.414 1.414L5.414 12H20a1 1 0 010 2H5.414l3.293 3.293a1 1 0 010 1.414zm3.293.377a1 1 0 011-1h7a1 1 0 010 2h-7a1 1 0 01-1-1z" clip-rule="evenodd"/></svg>`
};
