/* 🤖 this file was generated by svg-to-ts*/
export const upIconTl = {
    name: 'tl',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#TL_svg__clip0)"><path fill="#FFDA44" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#D80027" d="M24 0A23.901 23.901 0 008.57 5.619L34.435 24 8.57 42.381A23.901 23.901 0 0024 48c13.255 0 24-10.745 24-24S37.255 0 24 0z"/><path fill="#000" d="M7.029 7.03c-9.373 9.372-9.373 24.568 0 33.94L23.999 24 7.03 7.03z"/><path fill="#F0F0F0" d="M6.654 18.502l3.652 3.457 4.417-2.406-2.159 4.542 3.653 3.457-4.987-.65-2.159 4.542-.923-4.943-4.987-.65 4.416-2.406-.923-4.943z"/></g><defs><clipPath id="TL_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
