/* 🤖 this file was generated by svg-to-ts*/
export const upIconImportMedium = {
    name: 'import_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M12.708 17.665l3.999-3.999a1 1 0 10-1.414-1.414L13 14.545V4.959a1 1 0 10-2 0v9.586l-2.293-2.293a1 1 0 10-1.414 1.414l3.999 4a1 1 0 001.415 0zM4 12.96a1 1 0 10-2 0v7a2 2 0 002 2h16a2 2 0 002-2v-7a1 1 0 10-2 0v7H4v-7z" clip-rule="evenodd"/></svg>`
};
