/* 🤖 this file was generated by svg-to-ts*/
export const upIconCountrySelected = {
    name: 'country_selected',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20"><circle cx="10" cy="10" r="9.5" fill="#50E2D1" stroke="#50E2D1"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M6.25 10l2.5 2.5 5-5"/></svg>`
};
