/* 🤖 this file was generated by svg-to-ts*/
export const upIconDensityRelaxedSmall = {
    name: 'density_relaxed_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 14"><path fill="currentColor" fill-rule="evenodd" d="M0 1a1 1 0 011-1h14a1 1 0 110 2H1a1 1 0 01-1-1zm0 6a1 1 0 011-1h14a1 1 0 110 2H1a1 1 0 01-1-1zm1 5a1 1 0 100 2h14a1 1 0 100-2H1z" clip-rule="evenodd"/></svg>`
};
