/* 🤖 this file was generated by svg-to-ts*/
export const upIconArchiveLarge = {
    name: 'archive_large',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 32 32"><path fill="currentColor" fill-rule="evenodd" d="M27 7H5v4h22V7zM5 5a2 2 0 00-2 2v4a2 2 0 002 2v12a2 2 0 002 2h18a2 2 0 002-2V13a2 2 0 002-2V7a2 2 0 00-2-2H5zm2 8v12h18V13H7zm4 3a1 1 0 100 2h10a1 1 0 100-2H11z" clip-rule="evenodd"/></svg>`
};
