/* 🤖 this file was generated by svg-to-ts*/
export const upIconEmailMedium = {
    name: 'email_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M4 4.959a2 2 0 00-2 2v12a2 2 0 002 2h16a2 2 0 002-2v-12a2 2 0 00-2-2H4zm15.964 2H20V7l-.036-.041zm-1.436 0H5.472L12 12.67l6.528-5.712zm-14.492 0H4V7l.036-.041zM4 8.329v10.63h16V8.329l-7.341 6.424a1 1 0 01-1.318 0L4 8.329z" clip-rule="evenodd"/></svg>`
};
