/* 🤖 this file was generated by svg-to-ts*/
export const upIconLs = {
    name: 'ls',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#LS_svg__clip0)"><path fill="#F0F0F0" d="M0 24c0 3.74.856 7.28 2.381 10.435L24 35.478l21.619-1.043A23.906 23.906 0 0048 24c0-3.74-.856-7.28-2.381-10.435L24 12.522 2.381 13.565A23.905 23.905 0 000 24z"/><path fill="#6DA544" d="M24 48c9.515 0 17.736-5.537 21.618-13.565H2.381C6.263 42.463 14.485 48 24 48z"/><path fill="#0052B4" d="M24 0C14.485 0 6.263 5.537 2.38 13.565h43.237C41.736 5.537 33.515 0 24 0z"/><path fill="#000" d="M25.566 23.478V17.74h-3.13v5.74l-3.782 3.78A6.257 6.257 0 0024 30.261a6.257 6.257 0 005.347-3.002l-3.781-3.78z"/></g><defs><clipPath id="LS_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
