/* 🤖 this file was generated by svg-to-ts*/
export const upIconSortDownSmall = {
    name: 'sort_down_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M7.293 14.293a1 1 0 011.414 0L12 17.586l3.293-3.293a1 1 0 011.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"/><path fill="currentColor" fill-rule="evenodd" d="M11.293 4.293a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L12 6.414 8.707 9.707a1 1 0 01-1.414-1.414l4-4z" clip-rule="evenodd" opacity=".32"/></svg>`
};
