/* 🤖 this file was generated by svg-to-ts*/
export const upIconHomeMedium = {
    name: 'home_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M12.659 2.247a1 1 0 00-1.318 0l-8 7A1 1 0 003 10v9a3 3 0 003 3h12a3 3 0 003-3v-9a1 1 0 00-.341-.753l-8-7zM16 20h2a1 1 0 001-1v-8.546l-7-6.125-7 6.125V19a1 1 0 001 1h2v-7a1 1 0 011-1h6a1 1 0 011 1v7zm-6 0v-6h4v6h-4z" clip-rule="evenodd"/></svg>`
};
