/* 🤖 this file was generated by svg-to-ts*/
export const upIconInvoiceMedium = {
    name: 'invoice_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M7 2.959a2 2 0 00-2 2v6a1 1 0 002 0v-6h5.586L17 9.373V20.96h-5a1 1 0 100 2h5a2 2 0 002-2V9.373a2 2 0 00-.586-1.414L14 3.545a2 2 0 00-1.414-.586H7zm-2 19v-2H3a1 1 0 110-2h2v-2a1 1 0 112 0v2h2a1 1 0 110 2H7v2a1 1 0 01-2 0z" clip-rule="evenodd"/></svg>`
};
