/* 🤖 this file was generated by svg-to-ts*/
export const upIconGh = {
    name: 'gh',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#GH_svg__clip0)"><path fill="#FFDA44" d="M0 24c0 2.936.528 5.748 1.493 8.348L24 33.39l22.507-1.043A23.947 23.947 0 0048 24c0-2.936-.528-5.748-1.493-8.348L24 14.61 1.493 15.652A23.95 23.95 0 000 24z"/><path fill="#D80027" d="M24 0C13.68 0 4.882 6.513 1.491 15.652h45.014C43.117 6.513 34.319 0 24 0z"/><path fill="#496E2D" d="M46.506 32.348H1.492C4.883 41.487 13.68 48 23.999 48c10.32 0 19.116-6.513 22.507-15.652z"/><path fill="#000" d="M24 15.652l2.073 6.377h6.705l-5.424 3.942 2.072 6.377L24 28.407l-5.425 3.94 2.072-6.376-5.425-3.942h6.706L24 15.652z"/></g><defs><clipPath id="GH_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
