/* 🤖 this file was generated by svg-to-ts*/
export const upIconVn = {
    name: 'vn',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#D80027" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#FFDA44" d="M24 12.522l2.59 7.971h8.381l-6.78 4.927 2.59 7.971-6.782-4.926-6.78 4.926 2.59-7.971-6.781-4.927h8.381L24 12.522z"/></svg>`
};
