/* 🤖 this file was generated by svg-to-ts*/
export const upIconFullScreenMedium = {
    name: 'full_screen_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-opacity=".2" fill-rule="evenodd" d="M14 3a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 11-2 0V5.414l-5.793 5.793a1 1 0 01-1.414-1.414L18.586 4H15a1 1 0 01-1-1zM6 6a1 1 0 011-1h4a1 1 0 110 2H8v9h9v-3a1 1 0 112 0v4a1 1 0 01-1 1H7a1 1 0 01-1-1V6zm-2 4a1 1 0 00-2 0v11a1 1 0 001 1h11a1 1 0 100-2H4V10z" clip-rule="evenodd"/><path fill="currentColor" fill-rule="evenodd" d="M15 4a1 1 0 110-2h6a1 1 0 011 1v6a1 1 0 11-2 0V5.414l-5.793 5.793a1 1 0 01-1.414-1.414L18.586 4H15zM6 6a1 1 0 011-1h4a1 1 0 110 2H8v9h9v-3a1 1 0 112 0v4a1 1 0 01-1 1H7a1 1 0 01-1-1V6zM3 9a1 1 0 011 1v10h10a1 1 0 110 2H3a1 1 0 01-1-1V10a1 1 0 011-1z" clip-rule="evenodd"/></svg>`
};
