/* 🤖 this file was generated by svg-to-ts*/
export const upIconDeleteMedium = {
    name: 'delete_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M10 2.959a2 2 0 00-2 2v2H4a1 1 0 000 2h.08L5 20.005a3 3 0 003 2.954h8a3 3 0 003-2.954l.92-11.046H20a1 1 0 100-2h-4v-2a2 2 0 00-2-2h-4zm4 4v-2h-4v2h4zm-5 2H6.087l.91 10.917a1 1 0 01.003.083 1 1 0 001 1h8a1 1 0 001-1 1 1 0 01.003-.083l.91-10.917H9zm1 2a1 1 0 011 1v6a1 1 0 01-2 0v-6a1 1 0 011-1zm5 1a1 1 0 10-2 0v6a1 1 0 002 0v-6z" clip-rule="evenodd"/></svg>`
};
