/* 🤖 this file was generated by svg-to-ts*/
export const upIconPurchases = {
    name: 'purchases',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" d="M2 4a1 1 0 011-1h2.165a2 2 0 011.968 1.642L8.835 14h9.384l1.5-6H10a1 1 0 010-2h9.72a2 2 0 011.94 2.485l-1.5 6A2 2 0 0118.22 16H8.834a2 2 0 01-1.968-1.642L5.165 5H3a1 1 0 01-1-1z"/><path fill="currentColor" fill-rule="evenodd" d="M9 23a3 3 0 100-6 3 3 0 000 6zm0-2a1 1 0 100-2 1 1 0 000 2zM20 20a3 3 0 11-6 0 3 3 0 016 0zm-2 0a1 1 0 11-2 0 1 1 0 012 0z" clip-rule="evenodd"/></svg>`
};
