/* 🤖 this file was generated by svg-to-ts*/
export const upIconCommentsMedium = {
    name: 'comments_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M20 6.959H4v10h.9c1.16 0 2.1.94 2.1 2.1v1.014l3.577-2.555a3 3 0 011.743-.56H20v-10zm-16-2h16a2 2 0 012 2v10a2 2 0 01-2 2h-7.68a1 1 0 00-.58.186L6.58 22.83A1 1 0 015 22.016v-2.957a.1.1 0 00-.1-.1H4a2 2 0 01-2-2v-10a2 2 0 012-2zm2 5a1 1 0 011-1h10a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h7a1 1 0 000-2H7z" clip-rule="evenodd"/></svg>`
};
