/* 🤖 this file was generated by svg-to-ts*/
export const upIconMarkAsPaidMedium = {
    name: 'mark_as_paid_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="#312B78" fill-rule="evenodd" d="M4 4.959a2 2 0 00-2 2v12a2 2 0 002 2h16a2 2 0 002-2v-8a1 1 0 10-2 0v8H4v-7h5a1.5 1.5 0 000-3H4v-2h4a1 1 0 100-2H4zm2 11a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm10-1a1 1 0 100 2h1a1 1 0 000-2h-1z" clip-rule="evenodd"/><path fill="#50E2D1" fill-rule="evenodd" d="M21.707 3.252a1 1 0 010 1.414l-6 6a1 1 0 01-1.414 0l-3-3a1 1 0 011.414-1.414L15 8.545l5.293-5.293a1 1 0 011.414 0z" clip-rule="evenodd"/></svg>`
};
