/* 🤖 this file was generated by svg-to-ts*/
export const upIconFilterActiveMedium = {
    name: 'filter_active_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="#312B78" fill-rule="evenodd" d="M14.126 7.959H5a1 1 0 000 2h9.126a4.01 4.01 0 010-2zm1.228 4H8a1 1 0 100 2h8a1 1 0 00.992-1.128 3.99 3.99 0 01-1.638-.872zm-5.354 5a1 1 0 011-1h2a1 1 0 110 2h-2a1 1 0 01-1-1z" clip-rule="evenodd"/><path fill="#50E2D1" d="M20 8.959a2 2 0 11-4 0 2 2 0 014 0z"/></svg>`
};
