/* 🤖 this file was generated by svg-to-ts*/
export const upIconCz = {
    name: 'cz',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#CZ_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#D80027" d="M21.913 24S7.043 40.974 7.029 40.97A23.925 23.925 0 0024 48c13.255 0 24-10.745 24-24H21.913z"/><path fill="#0052B4" d="M7.029 7.03c-9.373 9.372-9.373 24.568 0 33.94L23.999 24 7.03 7.03z"/></g><defs><clipPath id="CZ_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
