/* 🤖 this file was generated by svg-to-ts*/
export const upIconPy = {
    name: 'py',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#PY_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#D80027" d="M24 0C14.485 0 6.263 5.537 2.38 13.565h43.237C41.736 5.537 33.515 0 24 0z"/><path fill="#0052B4" d="M24 48c9.515 0 17.736-5.537 21.618-13.565H2.381C6.263 42.463 14.485 48 24 48z"/><path fill="#6DA544" d="M29.904 17.054l-2.214 2.213a5.217 5.217 0 11-7.378 0l-2.214-2.213a8.348 8.348 0 1011.805 0z"/><path fill="#FFDA44" d="M24 19.826l.777 2.392h2.514l-2.034 1.477.777 2.392L24 24.609l-2.035 1.478.777-2.392-2.034-1.477h2.514L24 19.826z"/></g><defs><clipPath id="PY_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
