/* 🤖 this file was generated by svg-to-ts*/
export const upIconMinusMedium = {
    name: 'minus_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M8.5 7.002h-1L7 7H2a1 1 0 000 2h5l1 .002h1V9h5a1 1 0 100-2H9l-.5.002z" clip-rule="evenodd"/></svg>`
};
