/* 🤖 this file was generated by svg-to-ts*/
export const upIconApproveDocumentMedium = {
    name: 'approve_document_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" d="M7 2.959a2 2 0 00-2 2v5a1 1 0 002 0v-5h5.586L17 9.373V20.96h-1a1 1 0 100 2h1a2 2 0 002-2V9.373a2 2 0 00-.586-1.414L14 3.545a2 2 0 00-1.414-.586H7z"/><path fill="currentColor" d="M13.707 19.248A1 1 0 0013 17.541h-1.02A5 5 0 107 23a1 1 0 100-2 3 3 0 112.965-3.459H9a1 1 0 00-.707 1.707l2 2a1 1 0 001.414 0l2-2z"/></svg>`
};
