/* 🤖 this file was generated by svg-to-ts*/
export const upIconCl = {
    name: 'cl',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#CL_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#D80027" d="M48 24c0 13.255-10.745 24-24 24S0 37.255 0 24s24 0 24 0h24z"/><path fill="#0052B4" d="M0 24C0 10.745 10.745 0 24 0v24H0z"/><path fill="#F0F0F0" d="M14.287 8.348l1.554 4.783h5.029L16.8 16.087l1.554 4.783-4.069-2.956-4.068 2.956 1.554-4.783-4.069-2.956h5.03l1.553-4.783z"/></g><defs><clipPath id="CL_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
