/* 🤖 this file was generated by svg-to-ts*/
export const upIconClearSmall = {
    name: 'clear_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M2.75 8a5.25 5.25 0 1110.5 0 5.25 5.25 0 01-10.5 0zM8 1.25a6.75 6.75 0 100 13.5 6.75 6.75 0 000-13.5zM6.53 5.47a.75.75 0 00-1.06 1.06L6.94 8 5.47 9.47a.75.75 0 101.06 1.06L8 9.06l1.47 1.47a.75.75 0 101.06-1.06L9.06 8l1.47-1.47a.75.75 0 10-1.06-1.06L8 6.94 6.53 5.47z" clip-rule="evenodd"/></svg>`
};
