/* 🤖 this file was generated by svg-to-ts*/
export const upIconMoveLeftMedium = {
    name: 'move_left_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M10.293 7.252a1 1 0 111.414 1.414l-4.293 4.293 4.293 4.293a1 1 0 01-1.414 1.414l-5-5a1 1 0 010-1.414l5-5zm7 0a1 1 0 111.414 1.414l-4.293 4.293 4.293 4.293a1 1 0 01-1.414 1.414l-5-5a1 1 0 010-1.414l5-5z" clip-rule="evenodd"/></svg>`
};
