/* 🤖 this file was generated by svg-to-ts*/
export const upIconWarningIcon = {
    name: 'warning_icon',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 22 19"><path fill="currentColor" fill-rule="evenodd" d="M9.252 1.088c.762-1.372 2.735-1.372 3.497 0l8.3 14.94c.74 1.334-.223 2.972-1.748 2.972H2.7C1.175 19 .21 17.362.952 16.029l8.3-14.941zM11 2.059L2.7 17h16.6L11 2.06zM11 6a1 1 0 011 1v4.5a1 1 0 01-2 0V7a1 1 0 011-1zm1 9a1 1 0 10-2 0v.02a1 1 0 002 0V15z" clip-rule="evenodd"/></svg>`
};
