/* 🤖 this file was generated by svg-to-ts*/
export const upIconChevronRightMedium = {
    name: 'chevron_right_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M9.707 5.707a1 1 0 00-1.414 1.414l4.95 4.95-4.95 4.95a1 1 0 101.414 1.414l5.657-5.657a1 1 0 000-1.414L9.707 5.707z" clip-rule="evenodd"/></svg>`
};
