/* 🤖 this file was generated by svg-to-ts*/
export const upIconRearrangeMedium = {
    name: 'rearrange_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M7.293 8.666a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L12 5.373 8.707 8.666a1 1 0 01-1.414 0zm9.414 8.586a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 111.414-1.414L12 20.545l3.293-3.293a1 1 0 011.414 0zM4 11.959a1 1 0 100 2h16a1 1 0 000-2H4z" clip-rule="evenodd"/></svg>`
};
