/* 🤖 this file was generated by svg-to-ts*/
export const upIconSubscriptions = {
    name: 'subscriptions',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M10 3.959a1 1 0 00-2 0V5H5a2 2 0 00-2 2v14a2 2 0 002 2h5.019a8.506 8.506 0 01-1.267-2H5v-8.541h4.656a8.546 8.546 0 012.08-2H5V7h3v.959a1 1 0 102 0V7h4v.959a1 1 0 102 0V7h3v2.374c.71.218 1.382.527 2 .914V7a2 2 0 00-2-2h-3V3.959a1 1 0 10-2 0V5h-4V3.959zm.076 13.883a1 1 0 01.217-1.09l2-2a1 1 0 011.414 0l2 2A1 1 0 0115 18.459h-.965A3 3 0 1017 15a1 1 0 110-2 5 5 0 11-4.98 5.459H11a1 1 0 01-.924-.617z" clip-rule="evenodd"/></svg>`
};
