/* 🤖 this file was generated by svg-to-ts*/
export const upIconRestoreMedium = {
    name: 'restore_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M12.207 2.252a1 1 0 10-1.414 1.414l1.293 1.293H12a8 8 0 108 8 1 1 0 10-2 0 6 6 0 11-6-6h.086l-1.293 1.293a1 1 0 001.414 1.414l3-3a1 1 0 000-1.414l-3-3z" clip-rule="evenodd"/></svg>`
};
