/* 🤖 this file was generated by svg-to-ts*/
export const upIconInboxMedium = {
    name: 'inbox_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M13 3a1 1 0 10-2 0v7.586L9.707 9.293a1 1 0 00-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L13 10.586V3zM2 14a2 2 0 012-2h1.444a2 2 0 012 2v2h9.112v-2a2 2 0 012-2H20a2 2 0 012 2v6a2 2 0 01-2 2H4a2 2 0 01-2-2v-6zm2 0v6h16v-6h-1.444v2a2 2 0 01-2 2H7.444a2 2 0 01-2-2v-2H4z" clip-rule="evenodd"/></svg>`
};
