/* 🤖 this file was generated by svg-to-ts*/
export const upIconCg = {
    name: 'cg',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#CG_svg__clip0)"><path fill="#FFDA44" d="M13.01 45.342L30.641 30.64l14.7-17.631A24.107 24.107 0 0035.005 2.666L17.36 17.359 2.666 35.004A24.104 24.104 0 0013.01 45.342z"/><path fill="#D80027" d="M40.971 40.971c7.572-7.572 9.026-18.943 4.364-27.976l-32.34 32.34c9.033 4.661 20.404 3.208 27.976-4.364z"/><path fill="#6DA544" d="M7.028 7.029C-.543 14.6-1.997 25.972 2.665 35.005l32.34-32.34C25.971-1.997 14.6-.543 7.027 7.029z"/></g><defs><clipPath id="CG_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
