/* 🤖 this file was generated by svg-to-ts*/
export const upIconAmountLessThan30DMedium = {
    name: 'amount_less_than_30_d_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M7 4.959a2 2 0 012-2h5.586A2 2 0 0116 3.545l4.414 4.414A2 2 0 0121 9.373V20.96a2 2 0 01-2 2h-2v-2h2V9.373L14.586 4.96H9v2.009l-2 .007V4.959zm0 5a1 1 0 00-2 0v1H4a2 2 0 00-2 2v8a2 2 0 002 2h9a2 2 0 002-2v-8a2 2 0 00-2-2h-1v-1a1 1 0 10-2 0v1H7v-1zm6 4.818H4v6.182h9v-6.182zm-1 2.682a.5.5 0 00-.5-.5h-2a.5.5 0 00-.5.5v2a.5.5 0 00.5.5h2a.5.5 0 00.5-.5v-2z" clip-rule="evenodd"/></svg>`
};
