/* 🤖 this file was generated by svg-to-ts*/
export const upIconSc = {
    name: 'sc',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#SC_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#FFDA44" d="M40.2 6.294A23.912 23.912 0 0024 0c-1.023 0-2.03.064-3.019.188L9.391 13.565.759 30.012a23.853 23.853 0 002.51 6.086L24 24 40.2 6.294z"/><path fill="#6DA544" d="M43.981 37.297l-33.578 6.48A23.887 23.887 0 0024 48c8.337 0 15.679-4.25 19.981-10.703z"/><path fill="#D80027" d="M40.205 6.297L3.284 36.121a24.092 24.092 0 003.439 4.535L48 24c0-7.009-3.005-13.315-7.796-17.703z"/><path fill="#0052B4" d="M0 24c0 2.076.264 4.09.76 6.012L20.981.188C9.152 1.673 0 11.768 0 24z"/></g><defs><clipPath id="SC_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
