/* 🤖 this file was generated by svg-to-ts*/
export const upIconCloseMedium = {
    name: 'close_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M7 7l10 10m0-10L7 17"/></svg>`
};
