/* 🤖 this file was generated by svg-to-ts*/
export const upIconAlertHelpMedium = {
    name: 'alert_help_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M4 12a8 8 0 1116 0 8 8 0 01-16 0zm8-10C6.477 2 2 6.477 2 12s4.477 10 10 10 10-4.477 10-10S17.523 2 12 2zm-1.4 4.758a3.949 3.949 0 111.4 7.64 1 1 0 01.002-2 1.95 1.95 0 10-1.482-3.215A1 1 0 019 7.885a3.95 3.95 0 011.6-1.127zM12 15.5a1 1 0 011 1v.02a1 1 0 01-2 0v-.02a1 1 0 011-1z" clip-rule="evenodd"/></svg>`
};
