/* 🤖 this file was generated by svg-to-ts*/
export const upIconOutboxMedium = {
    name: 'outbox_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M12.707 2.293A.995.995 0 0012.01 2a.997.997 0 00-.716.293l-3 3a1 1 0 001.414 1.414L11 5.414V13a1 1 0 002 0V5.414l1.293 1.293a1 1 0 101.414-1.414l-3-3zM2 14a2 2 0 012-2h1.444a2 2 0 012 2v2h9.112v-2a2 2 0 012-2H20a2 2 0 012 2v6a2 2 0 01-2 2H4a2 2 0 01-2-2v-6zm2 0v6h16v-6h-1.444v2a2 2 0 01-2 2H7.444a2 2 0 01-2-2v-2H4z" clip-rule="evenodd"/></svg>`
};
