/* 🤖 this file was generated by svg-to-ts*/
export const upIconHt = {
    name: 'ht',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#A2001D" d="M48 24c0 13.255-10.745 24-24 24S0 37.255 0 24 24 0 24 0s24 10.745 24 24z"/><path fill="#0052B4" d="M0 24C0 10.745 10.745 0 24 0s24 10.745 24 24"/><path fill="#F0F0F0" d="M32.348 30.26L24 29.218l-8.348 1.044V17.739h16.696v12.522z"/><path fill="#0052B4" d="M24 29.217a4.174 4.174 0 100-8.348 4.174 4.174 0 000 8.348z"/><path fill="#A2001D" d="M24 27.13a2.087 2.087 0 100-4.174 2.087 2.087 0 000 4.174z"/><path fill="#6DA544" d="M20.87 19.826h6.26L24 22.956l-3.13-3.13z"/><path fill="#FFDA44" d="M25.043 21.913h-2.087v6.26h2.087v-6.26z"/><path fill="#6DA544" d="M27.34 27.548h-6.68l-5.008 2.713h16.696l-5.009-2.713z"/></svg>`
};
