/* 🤖 this file was generated by svg-to-ts*/
export const upIconNewFolderMedium = {
    name: 'new_folder_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M4 4.959a2 2 0 00-2 2v6a1 1 0 002 0v-6h3.586l1.707 1.707a1 1 0 00.707.293h10v10h-6a1 1 0 100 2h6a2 2 0 002-2v-10a2 2 0 00-2-2h-9.586L8.707 5.252A1 1 0 008 4.959H4zM7 13a1 1 0 011 1v3h3a1 1 0 110 2H8v3a1 1 0 11-2 0v-3H3a1 1 0 110-2h3v-3a1 1 0 011-1z" clip-rule="evenodd"/><path fill="currentColor" d="M4 4.959a2 2 0 00-2 2v6a1 1 0 002 0v-6h3.586l1.707 1.707a1 1 0 00.707.293h10v10h-6a1 1 0 100 2h6a2 2 0 002-2v-10a2 2 0 00-2-2h-9.586L8.707 5.252A1 1 0 008 4.959H4z"/><path fill="currentColor" d="M7 13a1 1 0 011 1v3h3a1 1 0 110 2H8v3a1 1 0 11-2 0v-3H3a1 1 0 110-2h3v-3a1 1 0 011-1z"/></svg>`
};
