/* 🤖 this file was generated by svg-to-ts*/
export const upIconZoomInMedium = {
    name: 'zoom_in_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M16 12a5 5 0 11-10 0 5 5 0 0110 0zm-.808 5.606a7 7 0 111.414-1.414l3.101 3.1a1 1 0 01-1.414 1.415l-3.1-3.1zM11 8.46a1 1 0 011 1v1.5h1.5a1 1 0 110 2H12v1.5a1 1 0 01-2 0v-1.5H8.5a1 1 0 010-2H10v-1.5a1 1 0 011-1z" clip-rule="evenodd"/></svg>`
};
