/* 🤖 this file was generated by svg-to-ts*/
export const upIconSy = {
    name: 'sy',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#SY_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#D80027" d="M24 0C13.68 0 4.882 6.513 1.491 15.652h45.015C43.115 6.513 34.318 0 23.999 0z"/><path fill="#000" d="M24 48c10.318 0 19.115-6.513 22.507-15.652H1.492C4.883 41.487 13.68 48 24 48z"/><path fill="#6DA544" d="M14.34 18.26l1.296 3.986h4.19l-3.39 2.464 1.295 3.986-3.39-2.464-3.39 2.464 1.294-3.986-3.39-2.464h4.19l1.296-3.985zM33.66 18.26l1.295 3.986h4.191l-3.39 2.464 1.295 3.986-3.39-2.464-3.391 2.464 1.295-3.986-3.39-2.464h4.19l1.295-3.985z"/></g><defs><clipPath id="SY_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
