/* 🤖 this file was generated by svg-to-ts*/
export const upIconIn = {
    name: 'in',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#IN_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#FF9811" d="M24 0C14.485 0 6.263 5.537 2.38 13.565h43.237C41.736 5.537 33.515 0 24 0z"/><path fill="#6DA544" d="M24 48c9.515 0 17.736-5.537 21.618-13.565H2.381C6.263 42.463 14.485 48 24 48z"/><path fill="#0052B4" d="M24 32.348a8.348 8.348 0 100-16.696 8.348 8.348 0 000 16.696z"/><path fill="#F0F0F0" d="M24 29.217a5.217 5.217 0 100-10.434 5.217 5.217 0 000 10.434z"/><path fill="#0052B4" d="M24 17.562l1.61 3.65 3.965-.431L27.22 24l2.356 3.219-3.966-.431-1.61 3.65-1.609-3.65-3.966.43L20.781 24l-2.357-3.22 3.966.432 1.61-3.65z"/></g><defs><clipPath id="IN_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
