/* 🤖 this file was generated by svg-to-ts*/
export const upIconCo = {
    name: 'co',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#CO_svg__clip0)"><path fill="#FFDA44" d="M0 24C0 10.745 10.745 0 24 0s24 10.745 24 24l-24 2.087L0 24z"/><path fill="#D80027" d="M3.212 36C7.362 43.173 15.117 48 24 48c8.883 0 16.639-4.827 20.789-12L24 34.435 3.212 36z"/><path fill="#0052B4" d="M44.788 36A23.889 23.889 0 0048 24H0c0 4.372 1.17 8.47 3.212 12h41.576z"/></g><defs><clipPath id="CO_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
