/* 🤖 this file was generated by svg-to-ts*/
export const upIconTd = {
    name: 'td',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#TD_svg__clip0)"><path fill="#FFDA44" d="M24 0c-2.936 0-5.748.528-8.348 1.493L14.61 24l1.043 22.507C18.252 47.472 21.064 48 24 48c2.936 0 5.748-.528 8.348-1.493L33.39 24 32.348 1.493A23.95 23.95 0 0024 0z"/><path fill="#D80027" d="M48 24c0-10.32-6.513-19.116-15.652-22.507v45.014C41.487 43.117 48 34.32 48 24z"/><path fill="#0052B4" d="M15.652 46.507V1.493C6.513 4.883 0 13.68 0 24c0 10.32 6.513 19.116 15.652 22.507z"/></g><defs><clipPath id="TD_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
