/* 🤖 this file was generated by svg-to-ts*/
export const upIconBankAccountsLarge = {
    name: 'bank_accounts_large',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 32 32"><path fill="currentColor" fill-rule="evenodd" d="M5 8h22v3H5V8zm0 6v10h22V14H5zM3 8a2 2 0 012-2h22a2 2 0 012 2v16a2 2 0 01-2 2H5a2 2 0 01-2-2V8zm4 9a1 1 0 011-1h8a1 1 0 110 2H8a1 1 0 01-1-1zm12-1a1 1 0 100 2h2a1 1 0 100-2h-2zM7 21a1 1 0 011-1h3a1 1 0 110 2H8a1 1 0 01-1-1zm7-1a1 1 0 100 2h1a1 1 0 100-2h-1zm3 1a1 1 0 011-1h2a1 1 0 110 2h-2a1 1 0 01-1-1zm6-1a1 1 0 100 2h1a1 1 0 100-2h-1z" clip-rule="evenodd"/></svg>`
};
