/* 🤖 this file was generated by svg-to-ts*/
export const upIconRu = {
    name: 'ru',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#RU_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#0052B4" d="M46.507 32.348A23.946 23.946 0 0048 24c0-2.936-.528-5.748-1.493-8.348H1.493A23.949 23.949 0 000 24c0 2.936.528 5.748 1.493 8.348L24 34.435l22.507-2.087z"/><path fill="#D80027" d="M24 48c10.318 0 19.115-6.513 22.506-15.652H1.492C4.883 41.487 13.68 48 23.999 48z"/></g><defs><clipPath id="RU_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
