/* 🤖 this file was generated by svg-to-ts*/
export const upIconChevronUpMedium = {
    name: 'chevron_up_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M5.707 13.364a1 1 0 101.414 1.414l4.95-4.95 4.95 4.95a1 1 0 001.414-1.414l-5.657-5.657a1 1 0 00-1.414 0l-5.657 5.657z" clip-rule="evenodd"/></svg>`
};
