/* 🤖 this file was generated by svg-to-ts*/
export const upIconBe = {
    name: 'be',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#BE_svg__clip0)"><path fill="#FFDA44" d="M32.348 1.493A23.948 23.948 0 0024 0c-2.936 0-5.748.528-8.348 1.493L13.565 24l2.087 22.507C18.252 47.472 21.064 48 24 48c2.936 0 5.748-.528 8.348-1.493L34.435 24 32.348 1.493z"/><path fill="#D80027" d="M48 24c0-10.32-6.513-19.116-15.652-22.507v45.014C41.487 43.117 48 34.32 48 24z"/><path fill="#000" d="M0 24c0 10.32 6.513 19.116 15.652 22.507V1.493C6.513 4.883 0 13.68 0 24z"/></g><defs><clipPath id="BE_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
