/* 🤖 this file was generated by svg-to-ts*/
export const upIconAmountOverdueMedium = {
    name: 'amount_overdue_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M7 4.959a2 2 0 012-2h5.586A2 2 0 0116 3.545l4.414 4.414A2 2 0 0121 9.373V20.96a2 2 0 01-2 2h-1.737a1.981 1.981 0 000-2H19V9.373L14.586 4.96H9v2.256a2.022 2.022 0 00-2 0V4.96zm2.761 5.161c-.755-1.402-2.767-1.402-3.522 0L.913 20.01c-.717 1.333.248 2.949 1.761 2.949h10.652c1.513 0 2.478-1.616 1.76-2.948L9.762 10.12zM8 11.068l5.326 9.89H2.674L8 11.069zm1 3.89a1 1 0 10-2 0v1.5a1 1 0 102 0v-1.5zM9 19a1 1 0 11-2 0 1 1 0 012 0z" clip-rule="evenodd"/></svg>`
};
