/* 🤖 this file was generated by svg-to-ts*/
export const upIconAlertHelpSmall = {
    name: 'alert_help_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M1.75 8a6.25 6.25 0 1112.5 0 6.25 6.25 0 01-12.5 0zM8 .25a7.75 7.75 0 100 15.5A7.75 7.75 0 008 .25zM6.967 4.061a2.93 2.93 0 111.04 5.671.75.75 0 01.001-1.5 1.431 1.431 0 10-1.088-2.36.75.75 0 01-1.14-.974c.32-.374.727-.662 1.187-.837zM8 10.62a.75.75 0 01.75.75v.014a.75.75 0 11-1.5 0v-.014a.75.75 0 01.75-.75z" clip-rule="evenodd"/></svg>`
};
