/* 🤖 this file was generated by svg-to-ts*/
export const upIconExportMedium = {
    name: 'export_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M16.707 7.293a1 1 0 11-1.414 1.414L13 6.414V16a1 1 0 11-2 0V6.414L8.707 8.707a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4zM4 12a1 1 0 10-2 0v7a2 2 0 002 2h16a2 2 0 002-2v-7a1 1 0 10-2 0v7H4v-7z" clip-rule="evenodd"/></svg>`
};
