/* 🤖 this file was generated by svg-to-ts*/
export const upIconCopyMedium = {
    name: 'copy_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M5 3.959a2 2 0 00-2 2v8a1 1 0 002 0v-8h8a1 1 0 100-2H5zM9 8a2 2 0 00-2 2v9a2 2 0 002 2h9a2 2 0 002-2v-9a2 2 0 00-2-2H9zm0 2h9v9H9v-9z" clip-rule="evenodd"/></svg>`
};
