/* 🤖 this file was generated by svg-to-ts*/
export const upIconLogoutSmall = {
    name: 'logout_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M9.333 2.917a.75.75 0 110 1.5H5.667a.25.25 0 00-.25.25v6.666c0 .138.112.25.25.25h3.666a.75.75 0 010 1.5H5.667a1.75 1.75 0 01-1.75-1.75V4.667c0-.967.783-1.75 1.75-1.75h3.666zm-1 4.333a.75.75 0 000 1.5h3.856l-.72.72a.75.75 0 001.061 1.06l1.991-1.99a.748.748 0 000-1.08l-1.99-1.99a.75.75 0 10-1.061 1.06l.72.72H8.332z" clip-rule="evenodd"/></svg>`
};
