/* 🤖 this file was generated by svg-to-ts*/
export const upIconBj = {
    name: 'bj',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#D80027" d="M15.652 21.913l2.087 25.26c1.996.538 4.095.827 6.261.827 13.255 0 24-10.745 24-24l-32.348-2.087z"/><path fill="#FFDA44" d="M15.652 24L17.74.827A24.026 24.026 0 0124 0c13.255 0 24 10.745 24 24H15.652z"/><path fill="#6DA544" d="M0 24c0 11.089 7.52 20.42 17.74 23.173V.827C7.52 3.58 0 12.91 0 24z"/></svg>`
};
