/* 🤖 this file was generated by svg-to-ts*/
export const upIconBf = {
    name: 'bf',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#D80027" d="M0 24C0 10.745 10.745 0 24 0s24 10.745 24 24c-1.043 0-24 3.13-24 3.13L0 24z"/><path fill="#6DA544" d="M48 24c0 13.255-10.745 24-24 24S0 37.255 0 24"/><path fill="#FFDA44" d="M24 15.652l1.813 5.58h5.867l-4.747 3.449 1.813 5.58L24 26.812l-4.747 3.449 1.813-5.58-4.746-3.449h5.867L24 15.652z"/></svg>`
};
