/* 🤖 this file was generated by svg-to-ts*/
export const upIconNl = {
    name: 'nl',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#NL_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#A2001D" d="M24 0C13.68 0 4.882 6.513 1.491 15.652h45.015C43.116 6.513 34.319 0 23.999 0z"/><path fill="#0052B4" d="M24 48c10.319 0 19.116-6.513 22.507-15.652H1.492C4.883 41.487 13.68 48 24 48z"/></g><defs><clipPath id="NL_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
