/* 🤖 this file was generated by svg-to-ts*/
export const upIconLv = {
    name: 'lv',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#A2001D" d="M24 0C12.913 0 3.582 7.52.828 17.74h46.347C44.42 7.52 35.089 0 24 0zM24 48c11.09 0 20.42-7.52 23.174-17.74H.827C3.581 40.48 12.912 48 24.001 48z"/></svg>`
};
