/* 🤖 this file was generated by svg-to-ts*/
export const upIconJp = {
    name: 'jp',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#D80027" d="M24 34.435c5.763 0 10.434-4.672 10.434-10.435 0-5.763-4.671-10.435-10.434-10.435-5.763 0-10.435 4.672-10.435 10.435 0 5.763 4.672 10.435 10.435 10.435z"/></svg>`
};
