/* 🤖 this file was generated by svg-to-ts*/
export const upIconMg = {
    name: 'mg',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#MG_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#6DA544" d="M15.652 24v22.507C18.252 47.472 21.064 48 24 48c13.255 0 24-10.745 24-24s-32.348 0-32.348 0z"/><path fill="#D80027" d="M24 0c-2.936 0-5.748.528-8.348 1.493V24H48C48 10.745 37.255 0 24 0z"/></g><defs><clipPath id="MG_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
