/* 🤖 this file was generated by svg-to-ts*/
export const upIconCloseSmall = {
    name: 'close_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" d="M4 4l8 8m0-8l-8 8"/></svg>`
};
