/* 🤖 this file was generated by svg-to-ts*/
export const upIconCommentAppendedMedium = {
    name: 'comment_appended_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M19 5.959H5v14h14v-14zm-14-2h14a2 2 0 012 2v14a2 2 0 01-2 2H5a2 2 0 01-2-2v-14a2 2 0 012-2zm2 5a1 1 0 011-1h8a1 1 0 110 2H8a1 1 0 01-1-1zm1 3a1 1 0 100 2h4a1 1 0 000-2H8z" clip-rule="evenodd"/></svg>`
};
