/* 🤖 this file was generated by svg-to-ts*/
export const upIconChevronDownSmall = {
    name: 'chevron_down_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M11.53 7.53a.75.75 0 00-1.06-1.06L8 8.94 5.53 6.47a.75.75 0 00-1.06 1.06l3 3a.75.75 0 001.06 0l3-3z" clip-rule="evenodd"/></svg>`
};
