/* 🤖 this file was generated by svg-to-ts*/
export const upIconLi = {
    name: 'li',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#D80027" d="M48 24c0 13.255-10.745 24-24 24S0 37.255 0 24c1.043 0 24-3.13 24-3.13L48 24z"/><path fill="#0052B4" d="M0 24C0 10.745 10.745 0 24 0s24 10.745 24 24"/><path fill="#FFDA44" d="M17.739 16.696a3.13 3.13 0 00-5.218-2.333v-1.841h1.044v-2.087H12.52V9.39h-2.087v1.044H9.391v2.087h1.043v1.841a3.13 3.13 0 00-4.174 4.665v1.842h10.435v-1.842a3.122 3.122 0 001.044-2.332z"/></svg>`
};
