/* 🤖 this file was generated by svg-to-ts*/
export const upIconMoveRightMedium = {
    name: 'move_right_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M6.707 7.252a1 1 0 10-1.414 1.414l4.293 4.293-4.293 4.293a1 1 0 101.414 1.414l5-5a1 1 0 000-1.414l-5-5zm7 0a1 1 0 10-1.414 1.414l4.293 4.293-4.293 4.293a1 1 0 001.414 1.414l5-5a1 1 0 000-1.414l-5-5z" clip-rule="evenodd"/></svg>`
};
