/* 🤖 this file was generated by svg-to-ts*/
export const upIconArrowUpMedium = {
    name: 'arrow_up_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M11 19.959a1 1 0 102 0V8.373l4.293 4.293a1 1 0 101.414-1.414l-6-6a1 1 0 00-1.414 0l-.005.005-5.995 5.995a1 1 0 101.414 1.414L11 8.373V19.96z" clip-rule="evenodd"/></svg>`
};
