/* 🤖 this file was generated by svg-to-ts*/
export const upIconDocCenterLarge = {
    name: 'doc_center_large',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 32 32"><path fill="currentColor" fill-rule="evenodd" d="M7 3a2 2 0 00-2 2v7a1 1 0 102 0V5h11v1.5A1.5 1.5 0 0019.5 8H27v3H14.229a1 1 0 100 2H27v4a1 1 0 002 0V8a2 2 0 00-2-2h-7V5a2 2 0 00-2-2H7zm2.924 11.31a1 1 0 00-1.413-.034L4.316 18.27a.997.997 0 000 1.458l4.195 3.995a1 1 0 101.379-1.448L7.5 20H19a1 1 0 100-2H7.5l2.39-2.276a1 1 0 00.034-1.414zm13.566 4.966a1 1 0 10-1.38 1.448L24.5 23H13a1 1 0 000 2h11.5l-2.39 2.276a1 1 0 101.38 1.448l4.188-3.99a.997.997 0 000-1.47l-4.189-3.988z" clip-rule="evenodd"/></svg>`
};
