/* 🤖 this file was generated by svg-to-ts*/
export const upIconKw = {
    name: 'kw',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#KW_svg__clip0)"><path fill="#F0F0F0" d="M46.507 32.348A23.948 23.948 0 0048 24c0-2.936-.528-5.748-1.493-8.348L24 13.565 1.493 15.652A23.948 23.948 0 000 24c0 2.936.528 5.748 1.493 8.348L24 34.435l22.507-2.087z"/><path fill="#D80027" d="M24 48c10.32 0 19.116-6.513 22.507-15.652H1.493C4.883 41.487 13.68 48 24 48z"/><path fill="#6DA544" d="M24 0C13.68 0 4.884 6.513 1.493 15.652h45.014C43.117 6.513 34.32 0 24 0z"/><path fill="#000" d="M7.029 7.03c-9.373 9.372-9.373 24.568 0 33.94l8.623-8.622V15.652L7.029 7.03z"/></g><defs><clipPath id="KW_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
