/* 🤖 this file was generated by svg-to-ts*/
export const upIconMv = {
    name: 'mv',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="#D80027" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#6DA544" d="M39.652 12.522H8.348v22.956h31.304V12.522z"/><path fill="#F0F0F0" d="M27.864 30.783a6.783 6.783 0 113.226-12.75 8.348 8.348 0 100 11.934c-.96.52-2.058.816-3.226.816z"/></svg>`
};
