/* 🤖 this file was generated by svg-to-ts*/
export const upIconSearchSmall = {
    name: 'search_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M3.5 6.75a3.25 3.25 0 116.5 0 3.25 3.25 0 01-6.5 0zM6.75 2a4.75 4.75 0 102.787 8.597l3.183 3.183a.75.75 0 101.06-1.06l-3.183-3.183A4.75 4.75 0 006.75 2z" clip-rule="evenodd"/></svg>`
};
