/* 🤖 this file was generated by svg-to-ts*/
export const upIconLt = {
    name: 'lt',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#LT_svg__clip0)"><path fill="#6DA544" d="M46.507 32.348A23.946 23.946 0 0048 24c0-2.936-.528-5.748-1.493-8.348L24 13.565 1.493 15.652A23.946 23.946 0 000 24c0 2.936.528 5.748 1.493 8.348L24 34.435l22.507-2.087z"/><path fill="#FFDA44" d="M46.506 15.652C43.116 6.513 34.318 0 24 0S4.883 6.513 1.492 15.652h45.014z"/><path fill="#D80027" d="M24 48c10.318 0 19.115-6.513 22.506-15.652H1.492C4.883 41.487 13.68 48 23.999 48z"/></g><defs><clipPath id="LT_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
