/* 🤖 this file was generated by svg-to-ts*/
export const upIconAe = {
    name: 'ae',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><g clip-path="url(#AE_svg__clip0)"><path fill="#F0F0F0" d="M24 48c13.255 0 24-10.745 24-24S37.255 0 24 0 0 10.745 0 24s10.745 24 24 24z"/><path fill="#000" d="M13.566 32.348l2.087 14.16C18.253 47.471 21.065 48 24 48c10.319 0 19.116-6.513 22.507-15.652H13.566z"/><path fill="#6DA544" d="M13.566 15.652l2.087-14.16A23.946 23.946 0 0124 0C34.32 0 43.117 6.513 46.508 15.652H13.566z"/><path fill="#A2001D" d="M0 24c0 10.32 6.513 19.116 15.652 22.507V1.493C6.513 4.883 0 13.68 0 24z"/></g><defs><clipPath id="AE_svg__clip0"><path fill="#fff" d="M0 0h48v48H0z"/></clipPath></defs></svg>`
};
