/* 🤖 this file was generated by svg-to-ts*/
export const upIconScanMedium = {
    name: 'scan_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 48 48"><path fill="currentColor" fill-rule="evenodd" d="M12 6h4v4h-4a2 2 0 00-2 2v4H6v-4a6 6 0 016-6zm20 0v4h4a2 2 0 012 2v4h4v-4a6 6 0 00-6-6h-4zm6 30a2 2 0 01-2 2h-4v4h4a6 6 0 006-6v-4h-4v4zm-28 0v-4H6v4a6 6 0 006 6h4v-4h-4a2 2 0 01-2-2zm6-21.083a2 2 0 000 4h16a2 2 0 100-4H16zM6 22a2 2 0 100 4h36a2 2 0 100-4H6zm10 6.917a2 2 0 000 4h16a2 2 0 100-4H16z" clip-rule="evenodd"/></svg>`
};
