/* 🤖 this file was generated by svg-to-ts*/
export const upIconDeactivateMedium = {
    name: 'deactivate_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M7.071 6.657a8 8 0 0111.23 11.23L7.072 6.658zm-1.409 1.42a8 8 0 0011.22 11.22L5.662 8.077zM12 2.958c-5.523 0-10 4.477-10 10s4.477 10 10 10 10-4.477 10-10-4.477-10-10-10z" clip-rule="evenodd"/></svg>`
};
