/* 🤖 this file was generated by svg-to-ts*/
export const upIconImageMedium = {
    name: 'image_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M2 6.959a2 2 0 012-2h16a2 2 0 012 2v12a2 2 0 01-2 2H4a2 2 0 01-2-2v-12zm18 0H4v12h16v-12zm-10.038 2a1 1 0 01.896.485l2.34 3.902 1.095-1.094a1 1 0 011.488.082l2 2.5a1 1 0 11-1.562 1.25l-1.302-1.628-1.21 1.21a1 1 0 01-1.565-.193l-2.062-3.438-2.186 4.371a1 1 0 11-1.788-.894l3-6a1 1 0 01.856-.552zm7.038 2a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"/></svg>`
};
