/* 🤖 this file was generated by svg-to-ts*/
export const upIconAccountsReceivableMedium = {
    name: 'accounts_receivable_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M7 2a2 2 0 00-2 2v3a1 1 0 002 0V4h5.586L17 8.414V20H7v-1a1 1 0 10-2 0v1a2 2 0 002 2h10a2 2 0 002-2V8.414A2 2 0 0018.414 7L14 2.586A2 2 0 0012.586 2H7zM5.293 9.293a1 1 0 011.414 1.414L5.414 12H13a1 1 0 110 2H5.414l1.293 1.293a1 1 0 11-1.414 1.414l-3-3a.998.998 0 01.001-1.415m2.999-3l-2.999 3 2.999-3z" clip-rule="evenodd"/></svg>`
};
