/* 🤖 this file was generated by svg-to-ts*/
export const upIconArrowDownMedium = {
    name: 'arrow_down_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M13 5.959a1 1 0 10-2 0v11.586l-4.293-4.293a1 1 0 00-1.414 1.414l6 6a.997.997 0 001.414 0l.002-.002.002-.002 5.996-5.996a1 1 0 00-1.414-1.414L13 17.545V5.959z" clip-rule="evenodd"/></svg>`
};
