/* 🤖 this file was generated by svg-to-ts*/
export const upIconZoomOutMedium = {
    name: 'zoom_out_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 25"><path fill="currentColor" fill-rule="evenodd" d="M11 17a5 5 0 100-10 5 5 0 000 10zm0 2a6.97 6.97 0 004.192-1.394l3.1 3.101a1 1 0 001.415-1.414l-3.1-3.1A7 7 0 1011 19zm-2.5-8.041a1 1 0 100 2h5a1 1 0 000-2h-5z" clip-rule="evenodd"/></svg>`
};
