/* 🤖 this file was generated by svg-to-ts*/
export const upIconTrailingArrowSmall = {
    name: 'trailing_arrow_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M3.333 7.333a.667.667 0 000 1.334h7.752l-2.89 2.889a.667.667 0 10.943.943L13.136 8.5l.002-.002a.667.667 0 000-.943l-.002-.002-3.998-3.998a.667.667 0 10-.943.943l2.835 2.834H3.333z" clip-rule="evenodd"/></svg>`
};
