/* 🤖 this file was generated by svg-to-ts*/
export const upIconTakePhotoMedium = {
    name: 'take_photo_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M8.72 4.959a2 2 0 00-1.897 1.367L6.28 7.96H5a3 3 0 00-3 3v8a3 3 0 003 3h14a3 3 0 003-3v-8a3 3 0 00-3-3h-1.28l-.543-1.633a2 2 0 00-1.898-1.367H8.721zm0 2h6.56l.543 1.632a2 2 0 001.898 1.368H19a1 1 0 011 1v8a1 1 0 01-1 1H5a1 1 0 01-1-1v-8a1 1 0 011-1h1.64a1.5 1.5 0 001.423-1.026L8.72 6.96zm1.28 7a2 2 0 114 0 2 2 0 01-4 0zm2-4a4 4 0 100 8 4 4 0 000-8z" clip-rule="evenodd"/></svg>`
};
