import * as Icons from '.'

export declare type IconType =
    'accountspayablelarge' |
    'accountspayablemedium' |
    'accountsreceivablelarge' |
    'accountsreceivablemedium' |
    'addsmall' |
    'addressmedium' |
    'admin' |
    'alertbellmedium' |
    'alerterrormedium' |
    'alerterrorsmall' |
    'alerthelpmedium' |
    'alerthelpsmall' |
    'alertinfomedium' |
    'alertinfosmall' |
    'alertsuccessmedium' |
    'alertsuccesssmall' |
    'alertwarningmedium' |
    'alertwarningsmall' |
    'alertsmedium' |
    'amountlessthan30dmedium' |
    'amountmorethan30dmedium' |
    'amountoverduemedium' |
    'amounttotaldollarmedium' |
    'amounttotaleuromedium' |
    'amounttotalpoundmedium' |
    'amounttotalyenmedium' |
    'approvedocumentmedium' |
    'appslarge' |
    'appsmedium' |
    'archivelarge' |
    'archivemedium' |
    'arrowdownmedium' |
    'arrowleftmedium' |
    'arrowrightmedium' |
    'arrowupmedium' |
    'attachmentmedium' |
    'attachmentsmall' |
    'authenticationlarge' |
    'backarrowmedium' |
    'badgemedium' |
    'bankaccountslarge' |
    'bankaccountsmedium' |
    'calendarsmall' |
    'cancelchangesmedium' |
    'catalog' |
    'changeaccountmedium' |
    'changephotomedium' |
    'checkmarkmedium' |
    'chevrondownmedium' |
    'chevrondownsmall' |
    'chevronleftmedium' |
    'chevronleftsmall' |
    'chevronrightmedium' |
    'chevronrightsmall' |
    'chevronupmedium' |
    'chevronupsmall' |
    'cleanupmedium' |
    'clearsmall' |
    'clientslarge' |
    'clientsmedium' |
    'clients' |
    'closemedium' |
    'closesmall' |
    'collapsemedium' |
    'commentappendedmedium' |
    'commentsmedium' |
    'companymedium' |
    'companysmall' |
    'comparemedium' |
    'configmedium' |
    'copymedium' |
    'countryplaceholder' |
    'countryselected' |
    'deactivatemedium' |
    'deletemedium' |
    'densitycondensedsmall' |
    'densityregularsmall' |
    'densityrelaxedsmall' |
    'detailsmedium' |
    'discount' |
    'doccenterlarge' |
    'doccentermedium' |
    'documentaltmedium' |
    'documentlinkmedium' |
    'documentnotlinkedmedium' |
    'documentpdfmedium' |
    'document' |
    'donemedium' |
    'downloadattachmentmedium' |
    'downloadmedium' |
    'editmedium' |
    'emailmedium' |
    'expandmedium' |
    'exportmedium' |
    'favouritemedium' |
    'federatedidentitylarge' |
    'filteractivemedium' |
    'filtersmall' |
    'firstpagelarge' |
    'firstpagemedium' |
    'firstpagesmall' |
    'fittoheightmedium' |
    'fittowidthmedium' |
    'fullscreenmedium' |
    'gotomedium' |
    'gridmedium' |
    'hidesmall' |
    'homelarge' |
    'homemedium' |
    'ideamedium' |
    'imagemedium' |
    'importmedium' |
    'inboxmedium' |
    'invitemedium' |
    'invoicemedium' |
    'keycloaklarge' |
    'kickstartmedium' |
    'languagemedium' |
    'lastpagelarge' |
    'lastpagemedium' |
    'lastpagesmall' |
    'leadingarrowsmall' |
    'linkmedium' |
    'lockmedium' |
    'logoacertawhite' |
    'logosdworxwhite' |
    'logoutsmall' |
    'maintenancelarge' |
    'markasacceptmedium' |
    'markaspaidmedium' |
    'messagemedium' |
    'minusmedium' |
    'missingdocumentlarge' |
    'missingstate' |
    'moveleftmedium' |
    'moverightmedium' |
    'movetomedium' |
    'multimedium' |
    'myaccountlarge' |
    'networkmedium' |
    'newfoldermedium' |
    'newsmedium' |
    'notificationerrorsmall' |
    'outboxmedium' |
    'paymedium' |
    'plusmedium' |
    'processmedium' |
    'productcatalogmedium' |
    'purchases' |
    'rearrangemedium' |
    'restoremedium' |
    'savemedium' |
    'scanmedium' |
    'searchmedium' |
    'searchsmall' |
    'securitylarge' |
    'serverrelatedlarge' |
    'sessionsmedium' |
    'settingslarge' |
    'settingsmedium' |
    'showsmall' |
    'sortdownsmall' |
    'sortmedium' |
    'sortsmall' |
    'sortupsmall' |
    'spinnermedium' |
    'splitmedium' |
    'subscriptions' |
    'syncmedium' |
    'takephotomedium' |
    'taskslarge' |
    'tasksmedium' |
    'template' |
    'trailingarrowsmall' |
    'trailingicon' |
    'uplogoname' |
    'uplogoshape' |
    'uplogotagline' |
    'uploadmedium' |
    'usermedium' |
    'usersmall' |
    'vatexemptmedium' |
    'verticaldotsmedium' |
    'warningicon' |
    'zoomindisabledmedium' |
    'zoominmedium' |
    'zoomoutmedium' |
    'ad' |
    'ae' |
    'af' |
    'ag' |
    'ai' |
    'al' |
    'am' |
    'ao' |
    'ar' |
    'as' |
    'at' |
    'au' |
    'aw' |
    'ax' |
    'az' |
    'ba' |
    'bb' |
    'bd' |
    'be' |
    'bf' |
    'bg' |
    'bh' |
    'bi' |
    'bj' |
    'bm' |
    'bn' |
    'bo' |
    'br' |
    'bs' |
    'bt' |
    'bw' |
    'by' |
    'bz' |
    'ca' |
    'cc' |
    'cd' |
    'cf' |
    'cg' |
    'ch' |
    'ci' |
    'ck' |
    'cl' |
    'cm' |
    'cn' |
    'co' |
    'cr' |
    'cu' |
    'cv' |
    'cx' |
    'cy' |
    'cz' |
    'de' |
    'dj' |
    'dk' |
    'dm' |
    'do' |
    'dz' |
    'ec' |
    'ee' |
    'eg' |
    'eh' |
    'er' |
    'es' |
    'et' |
    'fi' |
    'fj' |
    'fk' |
    'fm' |
    'fo' |
    'fr' |
    'ga' |
    'gb' |
    'gd' |
    'ge' |
    'gg' |
    'gh' |
    'gi' |
    'gl' |
    'gm' |
    'gn' |
    'gq' |
    'gr' |
    'gt' |
    'gu' |
    'gw' |
    'gy' |
    'hk' |
    'hn' |
    'hr' |
    'ht' |
    'hu' |
    'id' |
    'ie' |
    'il' |
    'im' |
    'in' |
    'io' |
    'iq' |
    'ir' |
    'is' |
    'it' |
    'je' |
    'jm' |
    'jo' |
    'jp' |
    'ke' |
    'kg' |
    'kh' |
    'ki' |
    'km' |
    'kn' |
    'kp' |
    'kw' |
    'ky' |
    'kz' |
    'la' |
    'lb' |
    'lc' |
    'li' |
    'lk' |
    'lr' |
    'ls' |
    'lt' |
    'lu' |
    'lv' |
    'ly' |
    'ma' |
    'mc' |
    'md' |
    'me' |
    'mf' |
    'mg' |
    'mh' |
    'mk' |
    'ml' |
    'mm' |
    'mn' |
    'mo' |
    'mp' |
    'mq' |
    'mr' |
    'ms' |
    'mt' |
    'mu' |
    'mv' |
    'mw' |
    'mx' |
    'my' |
    'mz' |
    'na' |
    'ne' |
    'nf' |
    'ng' |
    'ni' |
    'nl' |
    'no' |
    'np' |
    'nr' |
    'nu' |
    'nz' |
    'om' |
    'pa' |
    'pe' |
    'pf' |
    'pg' |
    'ph' |
    'pk' |
    'pl' |
    'pn' |
    'pr' |
    'ps' |
    'pt' |
    'pw' |
    'py' |
    'qa' |
    'ro' |
    'rs' |
    'ru' |
    'rw' |
    'sa' |
    'sb' |
    'sc' |
    'sd' |
    'se' |
    'sg' |
    'si' |
    'sk' |
    'sl' |
    'sm' |
    'sn' |
    'so' |
    'sr' |
    'ss' |
    'st' |
    'sv' |
    'sy' |
    'sz' |
    'tc' |
    'td' |
    'tg' |
    'th' |
    'tj' |
    'tk' |
    'tl' |
    'tm' |
    'tn' |
    'to' |
    'tr' |
    'tt' |
    'tv' |
    'tw' |
    'tz' |
    'ua' |
    'ug' |
    'us' |
    'uy' |
    'uz' |
    'va' |
    'vc' |
    've' |
    'vg' |
    'vi' |
    'vn' |
    'vu' |
    'ws' |
    'ye' |
    'za' |
    'zm' |
    'zw';

const iconArray = Object.values(Icons)
const iconKeys = Object.keys(Icons)

console.log(iconArray)
console.log(iconKeys)

const IconMap = {}

iconArray.map((icon, index) => IconMap[iconKeys[index].toLocaleLowerCase()] = icon)

export const getIconFromName = (iconName: IconType) => {
    return iconName && IconMap[iconName]()
}
export default IconMap

